specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Factory
    network: {{network}}
    source:
      address: "{{address}}"
      abi: Factory
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Factory
          file: ./abis/apeswap/Factory.json
        - name: TokenABI
          file: ./abis/apeswap/IERC20.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/mappings/factory.ts
  - kind: ethereum
    name: MasterChef
    network: {{network}}
    source:
      address: "{{masterChefAddress}}"
      abi: MasterChefSushiswap
      startBlock: {{masterChefStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - _CircularBuffer
        - RewardToken
      abis:
        - name: MasterChefSushiswap
          file: ./abis/sushiswap/MasterChefSushiswap.json
        - name: MasterChefApeswap
          file: ./abis/apeswap/MasterChefApeswap.json
        - name: TokenABI
          file: ./abis/sushiswap/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256)
          handler: handleWithdraw
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256)
          handler: handleEmergencyWithdraw
      file: ./protocols/apeswap/src/mappings/masterchef/reward.ts
  - kind: ethereum
    name: MasterChefV2
    network: {{network}}
    source:
      address: "{{masterChefV2Address}}"
      abi: MasterChefV2Sushiswap
      startBlock: {{masterChefV2StartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: 
        - _CircularBuffer
        - RewardToken
      abis:
        - name: MasterChefV2Sushiswap
          file: ./abis/sushiswap/MasterChefV2Sushiswap.json
        - name: MasterChefV2Apeswap
          file: ./abis/apeswap/MasterChefV2Apeswap.json
        - name: TokenABI
          file: ./abis/sushiswap/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256,indexed address)
          handler: handleDepositV2
        - event: Withdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleWithdrawV2
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleEmergencyWithdrawV2
      file: ./protocols/apeswap/src/mappings/masterchef/rewardV2.ts
templates:
  - kind: ethereum/contract
    name: Pair
    network: {{network}}
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities: []
      abis:
        - name: Pair
          file: ./abis/apeswap/Pair.json
        - name: Factory
          file: ./abis/apeswap/Factory.json
        - name: TokenABI
          file: ./abis/apeswap/IERC20.json
      eventHandlers:
        - event: Mint(indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,uint256,uint256,indexed address)
          handler: handleBurn
        - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync
          