specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: LRTDepositPool
    network: {{ network }}
    source:
      address: "{{ depositPool.address }}"
      abi: LRTDepositPool
      startBlock: {{ depositPool.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: LRTDepositPool
          file: ./abis/KelpDAO/LRTDepositPool.json
        - name: LRTWithdrawalManager
          file: ./abis/KelpDAO/LRTWithdrawalManager.json
        - name: RSETH
          file: ./abis/KelpDAO/RSETH.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # Mispriced Tokens
        - name: EGETH
          file: ./abis/Prices/EGETH.json
        - name: EigenpieMLRT
          file: ./abis/Prices/EigenpieMLRT.json
        - name: WBETH
          file: ./abis/Prices/WBETH.json
        - name: SFRAX
          file: ./abis/Prices/SFRAX.json
      eventHandlers:
        - event: AssetDeposit(indexed address,indexed address,uint256,uint256,string)
          handler: handleAssetDeposit
        - event: ETHDeposit(indexed address,uint256,uint256,string)
          handler: handleETHDeposit
      file: {{{ file }}}
  - kind: ethereum
    name: LRTWithdrawalManager
    network: {{ network }}
    source:
      address: "{{ withdrawalManager.address }}"
      abi: LRTWithdrawalManager
      startBlock: {{ withdrawalManager.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        - name: LRTDepositPool
          file: ./abis/KelpDAO/LRTDepositPool.json
        - name: LRTWithdrawalManager
          file: ./abis/KelpDAO/LRTWithdrawalManager.json
        - name: RSETH
          file: ./abis/KelpDAO/RSETH.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # Mispriced Tokens
        - name: EGETH
          file: ./abis/Prices/EGETH.json
        - name: EigenpieMLRT
          file: ./abis/Prices/EigenpieMLRT.json
        - name: WBETH
          file: ./abis/Prices/WBETH.json
        - name: SFRAX
          file: ./abis/Prices/SFRAX.json
      eventHandlers:
        - event: AssetWithdrawalQueued(indexed address,indexed address,uint256,indexed uint256)
          handler: handleAssetWithdrawalQueued
        - event: AssetWithdrawalFinalized(indexed address,indexed address,uint256,uint256)
          handler: handleAssetWithdrawalFinalized
      file: {{{ file }}}
