specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: LendingPoolAddressesProviderRegistry
    network: mainnet
    source:
      address: "0x52D306e36E3B6B02c153d0266ff0f85d18BCD413"
      abi: LendingPoolAddressesProviderRegistry
      startBlock: 11360920
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - AddressesProviderRegistered
      abis:
        - name: LendingPoolAddressesProviderRegistry
          file: ./abis/LendingPoolAddressesProviderRegistry.json
        - name: LendingPoolAddressesProvider
          file: ./abis/LendingPoolAddressesProvider.json
      eventHandlers:
        - event: AddressesProviderRegistered(indexed address)
          handler: handleAddressesProviderRegistered
      file: ./src/mappings/lendingPoolAddressProvider.ts
templates:
  - kind: ethereum/contract
    name: LendingPoolAddressesProvider
    network: mainnet
    source:
      abi: LendingPoolAddressesProvider
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LendingPoolAddressesProvider
      abis:
        - name: AaveIncentivesController
          file: ./abis/AaveIncentivesController.json
        - name: LendingPoolAddressesProvider
          file: ./abis/LendingPoolAddressesProvider.json
      eventHandlers:
        - event: ProxyCreated(bytes32,indexed address)
          handler: handleProxyCreated
        - event: PriceOracleUpdated(indexed address)
          handler: handlePriceOracleUpdated
        - event: LendingPoolUpdated(indexed address)
          handler: handleLendingPoolUpdated
        - event: LendingPoolConfiguratorUpdated(indexed address)
          handler: handleLendingPoolConfiguratorUpdated
        # - event: AddressSet(bytes32,indexed address,bool) #new
        #   handler: handleAddressSet
      file: ./src/mappings/lendingPoolAddressProvider.ts

  - kind: ethereum/contract
    name: LendingPool
    network: mainnet
    source:
      abi: LendingPool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Block
        - Account
        - Token
        - Market
        - Transaction
        - Transfer
        - Position
        - PositionSnapshot
      abis:
        - name: AaveIncentivesController
          file: ./abis/AaveIncentivesController.json
        - name: AToken
          file: ./abis/AToken.json
        - name: VariableDebtToken
          file: ./abis/VariableDebtToken.json
        - name: StableDebtToken
          file: ./abis/StableDebtToken.json
        - name: LendingPool
          file: ./abis/LendingPool.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: IPriceOracleGetter
          file: ./abis/IPriceOracleGetter.json
      eventHandlers:
        - event: Deposit(indexed address,address,indexed address,uint256,indexed uint16)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,indexed address,uint256)
          handler: handleWithdraw
        - event: Borrow(indexed address,address,indexed address,uint256,uint256,uint256,indexed uint16)
          handler: handleBorrow
        - event: Repay(indexed address,indexed address,indexed address,uint256)
          handler: handleRepay
        - event: LiquidationCall(indexed address,indexed address,indexed address,uint256,uint256,address,bool)
          handler: handleLiquidationCall
        - event: ReserveDataUpdated(indexed address,uint256,uint256,uint256,uint256,uint256)
          handler: handleReserveDataUpdated
        - event: ReserveUsedAsCollateralEnabled(indexed address,indexed address)
          handler: handleReserveUsedAsCollateralEnabled
        - event: ReserveUsedAsCollateralDisabled(indexed address,indexed address)
          handler: handleReserveUsedAsCollateralDisabled
      file: ./src/mappings/lendingPool.ts
  - kind: ethereum/contract
    name: LendingPoolConfigurator
    network: mainnet
    source:
      abi: LendingPoolConfigurator
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Block
        - Account
        - Token
        - Market
        - Transaction
        - Transfer
        - Position
        - PositionSnapshot
      abis:
        - name: AaveIncentivesController
          file: ./abis/AaveIncentivesController.json
        - name: AToken
          file: ./abis/AToken.json
        - name: LendingPoolConfigurator
          file: ./abis/LendingPoolConfigurator.json
        - name: LendingPool
          file: ./abis/LendingPool.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: IPriceOracleGetter
          file: ./abis/IPriceOracleGetter.json
      eventHandlers:
        - event: ReserveInitialized(indexed address,indexed address,address,address,address)
          handler: handleReserveInitialized
        - event: CollateralConfigurationChanged(indexed address,uint256,uint256,uint256)
          handler: handleCollateralConfigurationChanged
        - event: BorrowingEnabledOnReserve(indexed address,bool)
          handler: handleBorrowingEnabledOnReserve
        - event: BorrowingDisabledOnReserve(indexed address)
          handler: handleBorrowingDisabledOnReserve
        - event: ReserveActivated(indexed address)
          handler: handleReserveActivated
        - event: ReserveDeactivated(indexed address)
          handler: handleReserveDeactivated  
        - event: ReserveFactorChanged(indexed address,uint256)
          handler: handleReserveFactorChanged
      file: ./src/mappings/lendingPoolConfigurator.ts
  - kind: ethereum/contract
    name: AToken
    network: mainnet
    source:
      abi: AToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - AToken
      abis:
        - name: AToken
          file: ./abis/AToken.json
        - name: AaveIncentivesController
          file: ./abis/AaveIncentivesController.json
        - name: LendingPool
          file: ./abis/LendingPool.json
        - name: IPriceOracleGetter
          file: ./abis/IPriceOracleGetter.json
      eventHandlers:
        - event: Burn(indexed address,indexed address,uint256,uint256)
          handler: handleATokenBurn
        - event: Mint(indexed address,uint256,uint256)
          handler: handleATokenMint
      file: src/mappings/aToken.ts
