specVersion: 0.0.5
repository: https://github.com/messari/subgraphs
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{subgraphId}}
  block: {{graftStartBlock}}
{{/graftEnabled}}
schema:
  file: ./schema.graphql
dataSources:
  {{#poolRegistry}}
  - kind: ethereum
    name: {{ name }}
    network: {{ network }}
    source:
      address: "{{ address }}"
      startBlock: {{ startBlock }}
      abi: Registry
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - LiquidityPool
        - Registry
        - Factory
      abis:
        - name: Registry
          file: ./abis/Registry.json
        - name: PoolInfo
          file: ./abis/PoolInfo.json
        - name: Rewards
          file: ./abis/Rewards.json
        - name: Pool
          file: ./abis/Pool.json
        - name: Gauge
          file: ./abis/Gauge.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        - name: Minter
          file: ./abis/Minter.json
        - name: AddressProvider
          file: ./abis/AddressProvider.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        # Pool Registry events
        - event: PoolAdded(indexed address)
          handler: handlePoolAdded
        - event: PoolAdded(indexed address,bytes)
          handler: handlePoolAddedWithRate

        # Factory Pool Registry Events
        - event: BasePoolAdded(address)
          handler: handleBasePoolAdded
        - event: PlainPoolDeployed(address[4],uint256,uint256,address)
          handler: handlePlainPoolDeployed
        - event: MetaPoolDeployed(address,address,uint256,uint256,address)
          handler: handleMetaPoolDeployed
        - event: LiquidityGaugeDeployed(address,address)
          handler: handleLiquidityGaugeDeployed
        
        - event: CryptoPoolDeployed(address,address[2],uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,address)
          handler: handleCryptoPoolDeployed
        - event: LiquidityGaugeDeployed(address,address,address)
          handler: handleLiquidityGaugeDeployedWithToken
      file: ./src/mappings/registryMappings.ts
  {{/poolRegistry}}

  {{#missingOldPools}}
  - kind: ethereum
    name: {{ name }}
    network: {{ network }}
    source:
      address: "{{ address }}"
      startBlock: {{ startBlock }}
      abi: Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Registry
        - LiquidityPool
      abis:
        - name: Pool
          file: ./abis/Pool.json
        - name: Registry
          file: ./abis/Registry.json
        - name: PoolInfo
          file: ./abis/PoolInfo.json
        - name: Gauge
          file: ./abis/Gauge.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        - name: Rewards
          file: ./abis/Rewards.json
        - name: AddressProvider
          file: ./abis/AddressProvider.json
        - name: Minter
          file: ./abis/Minter.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: TokenExchange(indexed address,int128,uint256,int128,uint256)
          handler: handleTokenExchange
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        
        - event: TokenExchangeUnderlying(indexed address,int128,uint256,int128,uint256)
          handler: handleTokenExchangeUnderlying
          receipt: true
        
        - event: AddLiquidity(indexed address,uint256[3],uint256,uint256)
          handler: handleAddLiquidity
        - event: AddLiquidity(indexed address,uint256[2],uint256[2],uint256,uint256)
          handler: handleAddLiquidityWithFees
        - event: AddLiquidity(indexed address,uint256[3],uint256[3],uint256,uint256)
          handler: handleAddLiquidityWithFees
        - event: AddLiquidity(indexed address,uint256[4],uint256[4],uint256,uint256)
          handler: handleAddLiquidityWithFees
        
        - event: RemoveLiquidity(indexed address,uint256[2],uint256)
          handler: handleRemoveLiquidity
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[3],uint256)
          handler: handleRemoveLiquidity
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[2],uint256[2],uint256)
          handler: handleRemoveLiquidityWithFees
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[3],uint256[3],uint256)
          handler: handleRemoveLiquidityWithFees
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[4],uint256[4],uint256)
          handler: handleRemoveLiquidityWithFees
          receipt: true
        
        - event: RemoveLiquidityOne(indexed address,uint256,uint256)
          handler: handleRemoveLiquidityOne
          receipt: true
        - event: RemoveLiquidityOne(indexed address,uint256,uint256,uint256)
          handler: handleRemoveLiquidityOneWithSupply
          receipt: true
        
        - event: RemoveLiquidityImbalance(indexed address,uint256[2],uint256[2],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
          receipt: true
        - event: RemoveLiquidityImbalance(indexed address,uint256[3],uint256[3],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
          receipt: true
        - event: RemoveLiquidityImbalance(indexed address,uint256[4],uint256[4],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
          receipt: true
      file: ./src/mappings/poolMappings.ts
  {{/missingOldPools}}

  - name: GaugeController
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: GaugeController
      address: "{{ gaugeControllerContract }}"
      startBlock: {{ gaugeControllerStartBlock }}

    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      abis:
        - name: GaugeController
          file: ./abis/GaugeController.json
        - name: Registry
          file: ./abis/Registry.json
        - name: Pool
          file: ./abis/Pool.json
        - name: Gauge
          file: ./abis/Gauge.json
        - name: Rewards
          file: ./abis/Rewards.json
        - name: Minter
          file: ./abis/Minter.json
        - name: AddressProvider
          file: ./abis/AddressProvider.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      entities:
        - Account
      eventHandlers:
        - event: NewGauge(address,int128,uint256)
          handler: handleNewGauge
        - event: DeployedGauge(indexed address,indexed address,indexed address,bytes32,address)
          handler: handleDeployedGauge
      file: ./src/mappings/gaugeControllerMappings.ts
  

templates:
  - name: PoolTemplate
    kind: ethereum
    network: {{ network }}
    source:
      abi: Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Registry
        - LiquidityPool
      abis:
        - name: Pool
          file: ./abis/Pool.json
        - name: Registry
          file: ./abis/Registry.json
        - name: PoolInfo
          file: ./abis/PoolInfo.json
        - name: Gauge
          file: ./abis/Gauge.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        - name: Rewards
          file: ./abis/Rewards.json
        - name: AddressProvider
          file: ./abis/AddressProvider.json
        - name: Minter
          file: ./abis/Minter.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: TokenExchange(indexed address,int128,uint256,int128,uint256)
          handler: handleTokenExchange
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        
        - event: TokenExchangeUnderlying(indexed address,int128,uint256,int128,uint256)
          handler: handleTokenExchangeUnderlying
          receipt: true
        
        - event: AddLiquidity(indexed address,uint256[3],uint256,uint256)
          handler: handleAddLiquidity
        - event: AddLiquidity(indexed address,uint256[2],uint256[2],uint256,uint256)
          handler: handleAddLiquidityWithFees
        - event: AddLiquidity(indexed address,uint256[3],uint256[3],uint256,uint256)
          handler: handleAddLiquidityWithFees
        - event: AddLiquidity(indexed address,uint256[4],uint256[4],uint256,uint256)
          handler: handleAddLiquidityWithFees
        
        - event: RemoveLiquidity(indexed address,uint256[2],uint256)
          handler: handleRemoveLiquidity
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[3],uint256)
          handler: handleRemoveLiquidity
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[2],uint256[2],uint256)
          handler: handleRemoveLiquidityWithFees
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[3],uint256[3],uint256)
          handler: handleRemoveLiquidityWithFees
          receipt: true
        - event: RemoveLiquidity(indexed address,uint256[4],uint256[4],uint256)
          handler: handleRemoveLiquidityWithFees
          receipt: true
        
        - event: RemoveLiquidityOne(indexed address,uint256,uint256)
          handler: handleRemoveLiquidityOne
          receipt: true
        - event: RemoveLiquidityOne(indexed address,uint256,uint256,uint256)
          handler: handleRemoveLiquidityOneWithSupply
          receipt: true
        
        - event: RemoveLiquidityImbalance(indexed address,uint256[2],uint256[2],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
          receipt: true
        - event: RemoveLiquidityImbalance(indexed address,uint256[3],uint256[3],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
          receipt: true
        - event: RemoveLiquidityImbalance(indexed address,uint256[4],uint256[4],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
          receipt: true
      file: ./src/mappings/poolMappings.ts
  
  - name: LiquidityGauge
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: Gauge
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - LiquidityPool
        - Registry
        - Factory
      abis:
        - name: Gauge
          file: ./abis/Gauge.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        - name: Pool
          file: ./abis/Pool.json
        - name: Registry
          file: ./abis/Registry.json
        - name: PoolInfo
          file: ./abis/PoolInfo.json
        - name: Rewards
          file: ./abis/Rewards.json
        - name: AddressProvider
          file: ./abis/AddressProvider.json
        - name: Minter
          file: ./abis/Minter.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256)
          handler: handleWithdraw
      file: ./src/mappings/gaugeMappings.ts
