specVersion: 0.0.5
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: arweave
    name: arweave-blocks
    network: {{ network }}
    source:
      owner: "ID-OF-AN-OWNER" # The public key of an Arweave wallet
      startBlock: 0 # set this to 0 to start indexing from chain genesis
    mapping:
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      eentities:
        - Network
        - Block
        - Author
      blockHandlers:
        - handler: handleBlock # the function name in the mapping file
      file: ./src/mapping.ts
