specVersion: 0.0.4
description: Bancor V3
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: BancorNetwork
    network: mainnet
    source:
      address: "0xeEF417e1D5CC832e619ae18D2F140De2999dD4fB"
      abi: BancorNetwork
      startBlock: 14609379
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - DexAmmProtocol
        - LiquidityPool
        - Token
        - Swap
      abis:
        - name: BancorNetwork
          file: ./abis/BancorNetwork.json
        - name: PoolToken
          file: ./abis/PoolToken.json
        - name: BancorNetworkInfo
          file: ./abis/BancorNetworkInfo.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: PoolCollectionAdded(indexed uint16,indexed address)
          handler: handlePoolCollectionAdded
        - event: TokensTraded(indexed bytes32,indexed address,indexed address,uint256,uint256,uint256,uint256,uint256,address)
          handler: handleTokensTraded
  - kind: ethereum/contract
    name: PoolTokenFactory
    network: mainnet
    source:
      address: "0x9e912953db31fe933bda43374208e967058d9d5f"
      abi: PoolTokenFactory
      startBlock: 14609357
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - DexAmmProtocol
        - LiquidityPool
        - Token
      abis:
        - name: PoolTokenFactory
          file: ./abis/PoolTokenFactory.json
        - name: PoolToken
          file: ./abis/PoolToken.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: PoolTokenCreated(indexed address,indexed address)
          handler: handlePoolTokenCreated
  - kind: ethereum/contract
    name: NetworkSettings
    network: mainnet
    source:
      address: "0x83E1814ba31F7ea95D216204BB45FE75Ce09b14F"
      abi: NetworkSettings
      startBlock: 14609373
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - DexAmmProtocol
      abis:
        - name: NetworkSettings
          file: ./abis/NetworkSettings.json
      eventHandlers:
        - event: NetworkFeePPMUpdated(uint32,uint32)
          handler: handleNetworkFeePPMUpdated
        - event: WithdrawalFeePPMUpdated(uint32,uint32)
          handler: handleWithdrawalFeePPMUpdated
  - kind: ethereum/contract
    name: StandardRewards
    network: mainnet
    source:
      address: "0xb0B958398ABB0b5DB4ce4d7598Fb868f5A00f372"
      abi: StandardRewards
      startBlock: 14609468
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - LiquidityPool
      abis:
        - name: StandardRewards
          file: ./abis/StandardRewards.json
        - name: BancorNetworkInfo
          file: ./abis/BancorNetworkInfo.json
      eventHandlers:
        - event: ProgramCreated(indexed address,indexed uint256,indexed address,uint256,uint32,uint32)
          handler: handleProgramCreated
        - event: ProgramTerminated(indexed address,indexed uint256,uint32,uint256)
          handler: handleProgramTerminated
        - event: ProgramEnabled(indexed address,indexed uint256,bool,uint256)
          handler: handleProgramEnabled
  - kind: ethereum/contract
    name: BNTPool
    network: mainnet
    source:
      address: "0x02651E355D26f3506C1E644bA393FDD9Ac95EaCa"
      abi: BNTPool
      startBlock: 14609387
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - Deposit
        - Withdraw
      abis:
        - name: BNTPool
          file: ./abis/BNTPool.json
        - name: BancorNetworkInfo
          file: ./abis/BancorNetworkInfo.json
      eventHandlers:
        - event: TokensDeposited(indexed bytes32,indexed address,uint256,uint256,uint256)
          handler: handleBNTDeposited
        - event: TokensWithdrawn(indexed bytes32,indexed address,uint256,uint256,uint256,uint256)
          handler: handleBNTWithdrawn
        - event: TotalLiquidityUpdated(indexed bytes32,uint256,uint256,uint256)
          handler: handleBNTTotalLiquidityUpdated
templates:
  - kind: ethereum/contract
    name: PoolCollection
    network: mainnet
    source:
      abi: PoolCollection
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - Deposit
        - Withdraw
      abis:
        - name: PoolCollection
          file: ./abis/PoolCollection.json
        - name: BancorNetworkInfo
          file: ./abis/BancorNetworkInfo.json
      eventHandlers:
        - event: TokensDeposited(indexed bytes32,indexed address,indexed address,uint256,uint256)
          handler: handleTokensDeposited
        - event: TokensWithdrawn(indexed bytes32,indexed address,indexed address,uint256,uint256,uint256,uint256,uint256)
          handler: handleTokensWithdrawn
        - event: TotalLiquidityUpdated(indexed bytes32,indexed address,uint256,uint256,uint256)
          handler: handleTotalLiquidityUpdated
        - event: DefaultTradingFeePPMUpdated(uint32,uint32)
          handler: handleDefaultTradingFeePPMUpdated
        - event: TradingFeePPMUpdated(indexed address,uint32,uint32)
          handler: handleTradingFeePPMUpdated
