specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: RariGovernor
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: RariGovernor
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: RariGovernor
          file: ./abis/rarible-governance/RariGovernor.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
          handler: handleProposalCreated
        - event: ProposalExecuted(uint256)
          handler: handleProposalExecuted
        - event: ProposalQueued(uint256,uint256)
          handler: handleProposalQueued
        - event: QuorumNumeratorUpdated(uint256,uint256)
          handler: handleQuorumNumeratorUpdated
        - event: TimelockChange(address,address)
          handler: handleTimelockChange
        - event: VoteCast(indexed address,uint256,uint8,uint256,string)
          handler: handleVoteCast
        - event: VoteCastWithParams(indexed address,uint256,uint8,uint256,string,bytes)
          handler: handleVoteCastWithParams
      file: ./protocols/rarible-governance/src/RariGovernor.ts
  - kind: ethereum/contract
    name: Staking
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: Staking
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: Staking
          file: ./abis/rarible-governance/Staking.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,indexed address)
          handler: handleDelegateChanged
        - event: DelegateVotesChanged(indexed address,uint256,uint256)
          handler: handleDelegateVotesChanged
        # Staking token is Non-ERC20 
        # - event: Transfer(indexed address,indexed address,uint256)
        #   handler: handleTransfer 
      file: ./protocols/rarible-governance/src/Staking.ts