specVersion: 0.0.2
description: Pangolin is a decentralized exchange for swapping Ethereum and Avalanche assets on Avalanche.
repository: https://github.com/pangolindex/subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Factory
    network: avalanche
    source:
      address: "0xefa94DE7a4656D787667C749f7E1223D71E9FD88"
      abi: Factory
      startBlock: 56877
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.3
      language: wasm/assemblyscript
      file: ./mappings/factory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: Factory
          file: ./abis/pangolin/Factory.json
        - name: ERC20
          file: ./abis/pangolin/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/pangolin/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/pangolin/ERC20NameBytes.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handleNewPair
  - kind: ethereum/contract
    name: MiniChefV2
    network: avalanche
    source:
      address: "0x1f806f7C8dED893fd3caE279191ad7Aa3798E928"
      abi: MiniChefV2
      startBlock: 7281230
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.3
      language: wasm/assemblyscript
      file: ./mappings/miniChefV2.ts
      entities:
        - Farm
        - Reward
      abis:
        - name: MiniChefV2
          file: ./abis/pangolin/MiniChefV2.json
        - name: RewarderViaMultiplier
          file: ./abis/pangolin/RewarderViaMultiplier.json
      eventHandlers:
        - event: PoolAdded(indexed uint256,uint256,indexed address,indexed address)
          handler: handlePoolAdded
        - event: Deposit(indexed address,indexed uint256,uint256,indexed address)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleWithdraw
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleEmergencyWithdraw
        - event: PoolSet(indexed uint256,uint256,indexed address,bool)
          handler: handlePoolSet
        - event: LogRewardPerSecond(uint256)
          handler: handleLogRewardPerSecond
        - event: LogRewardsExpiration(uint256)
          handler: handleLogRewardsExpiration
templates:
  - kind: ethereum/contract
    name: Pair
    network: avalanche
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.3
      language: wasm/assemblyscript
      file: ./mappings/core.ts
      entities:
        - Pair
        - Token
      abis:
        - name: Pair
          file: ./abis/pangolin/Pair.json
        - name: Factory
          file: ./abis/pangolin/Factory.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync