specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: NounsDAOLogicV2
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: NounsDAOLogicV2
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: NounsDAOLogicV2
          file: ./abis/nouns-governance/NounsDAOLogicV2.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
          handler: handleProposalCreated
        - event: ProposalCreatedWithRequirements(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,uint256,uint256,string)
          handler: handleProposalCreatedWithRequirements
        - event: ProposalExecuted(uint256)
          handler: handleProposalExecuted
        - event: ProposalQueued(uint256,uint256)
          handler: handleProposalQueued
        - event: ProposalThresholdBPSSet(uint256,uint256)
          handler: handleProposalThresholdSet
        - event: ProposalVetoed(uint256)
          handler: handleProposalCanceled
        - event: VoteCast(indexed address,uint256,uint8,uint256,string)
          handler: handleVoteCast
        - event: VotingDelaySet(uint256,uint256)
          handler: handleVotingDelaySet
        - event: VotingPeriodSet(uint256,uint256)
          handler: handleVotingPeriodSet
      file: ./protocols/nouns-governance/src/nouns-dao.ts
  - kind: ethereum/contract
    name: Nouns
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: Nouns
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: Nouns
          file: ./abis/nouns-governance/NounsToken.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,indexed address)
          handler: handleDelegateChanged
        - event: DelegateVotesChanged(indexed address,uint256,uint256)
          handler: handleDelegateVotesChanged
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./protocols/nouns-governance/src/nouns-token.ts
