specVersion: 0.0.4
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: LendingPoolAddressesProvider
    network: {{ network }}
    source:
      address: "{{ factory.address }}"
      abi: LendingPoolAddressesProvider
      startBlock: {{ factory.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - LendingProtocol
        - Market
      abis:
        - name: LendingPoolAddressesProvider
          file: ./abis/LendingPoolAddressesProvider.json
      eventHandlers:
        - event: PriceOracleUpdated(indexed address)
          handler: handlePriceOracleUpdated
      file: ./protocols/radiant-capital-v2/src/mapping.ts
  - kind: ethereum/contract
    name: LendingPool
    network: {{ network }}
    source:
      address: "{{ lendingPool.address }}"
      abi: LendingPool
      startBlock: {{ lendingPool.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Market
        - Deposit
        - Withdraw
        - Borrow
        - Repay
        - Liquidate
      abis:
        - name: ChefIncentivesController
          file: ./abis/radiant-capital/ChefIncentivesController.json
        - name: RToken
          file: ./abis/radiant-capital/RToken.json
        - name: AToken
          file: ./abis/aave-v2/AToken.json
        - name: VariableDebtToken
          file: ./abis/VariableDebtToken.json
        - name: StableDebtToken
          file: ./abis/StableDebtToken.json
        - name: LendingPool
          file: ./abis/radiant-capital/LendingPoolRadiant.json # custom LiquidationCall event
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: IPriceOracleGetter
          file: ./abis/IPriceOracleGetter.json
      eventHandlers:
        - event: Deposit(indexed address,address,indexed address,uint256,indexed uint16)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,indexed address,uint256)
          handler: handleWithdraw
        - event: Borrow(indexed address,address,indexed address,uint256,uint256,uint256,indexed uint16)
          handler: handleBorrow
        - event: Repay(indexed address,indexed address,indexed address,uint256)
          handler: handleRepay
        - event: LiquidationCall(indexed address,indexed address,indexed address,uint256,uint256,address,bool,address)
          handler: handleLiquidationCall
        - event: ReserveDataUpdated(indexed address,uint256,uint256,uint256,uint256,uint256)
          handler: handleReserveDataUpdated
        - event: ReserveUsedAsCollateralEnabled(indexed address,indexed address)
          handler: handleReserveUsedAsCollateralEnabled
        - event: ReserveUsedAsCollateralDisabled(indexed address,indexed address)
          handler: handleReserveUsedAsCollateralDisabled
        - event: Paused()
          handler: handlePaused
        - event: Unpaused()
          handler: handleUnpaused
      file: ./protocols/radiant-capital-v2/src/mapping.ts
  - kind: ethereum/contract
    name: LendingPoolConfigurator
    network: {{ network }}
    source:
      address: "{{ lendingPoolConfigurator.address }}"
      abi: LendingPoolConfigurator
      startBlock: {{ lendingPoolConfigurator.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Market
      abis:
        - name: RToken
          file: ./abis/radiant-capital/RToken.json
        - name: LendingPoolConfigurator
          file: ./abis/LendingPoolConfigurator.json
        - name: LendingPool
          file: ./abis/radiant-capital/LendingPoolRadiant.json # custom LiquidationCall event
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
      eventHandlers:
        - event: ReserveInitialized(indexed address,indexed address,address,address,address)
          handler: handleReserveInitialized
        - event: CollateralConfigurationChanged(indexed address,uint256,uint256,uint256)
          handler: handleCollateralConfigurationChanged
        - event: BorrowingEnabledOnReserve(indexed address,bool)
          handler: handleBorrowingEnabledOnReserve
        - event: BorrowingDisabledOnReserve(indexed address)
          handler: handleBorrowingDisabledOnReserve
        - event: ReserveActivated(indexed address)
          handler: handleReserveActivated
        - event: ReserveDeactivated(indexed address)
          handler: handleReserveDeactivated
        - event: ReserveFactorChanged(indexed address,uint256)
          handler: handleReserveFactorChanged
      file: ./protocols/radiant-capital-v2/src/mapping.ts
templates:
  - kind: ethereum/contract
    name: AToken
    network: {{ network }}
    source:
      abi: AToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: AToken
          file: ./abis/aave-v2/AToken.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleCollateralTransfer
      file: ./protocols/radiant-capital-v2/src/mapping.ts
  - kind: ethereum/contract
    name: VariableDebtToken
    network: {{ network }}
    source:
      abi: VariableDebtToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: VariableDebtToken
          file: ./abis/VariableDebtToken.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleVariableTransfer
      file: ./protocols/radiant-capital-v2/src/mapping.ts
  - kind: ethereum/contract
    name: StableDebtToken
    network: {{ network }}
    source:
      abi: StableDebtToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: StableDebtToken
          file: ./abis/StableDebtToken.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleStableTransfer
      file: ./protocols/radiant-capital-v2/src/mapping.ts
