export namespace Deploy {
    export const APESWAP_BSC = "APESWAP_BSC";
    export const APESWAP_MATIC = "APESWAP_MATIC";
    export const SUSHISWAP_ARBITRUM = "SUSHISWAP_ARBITRUM";
    export const SUSHISWAP_AVALANCHE = "SUSHISWAP_AVALANCHE";
    export const SUSHISWAP_BSC = "SUSHISWAP_BSC";
    export const SUSHISWAP_CELO = "SUSHISWAP_CELO";
    export const SUSHISWAP_FANTOM = "SUSHISWAP_FANTOM";
    export const SUSHISWAP_FUSE = "SUSHISWAP_FUSE";
    export const SUSHISWAP_MAINNET = "SUSHISWAP_MAINNET";
    export const SUSHISWAP_MATIC = "SUSHISWAP_MATIC";
    export const SUSHISWAP_MOONBEAM = "SUSHISWAP_MOONBEAM";
    export const SUSHISWAP_MOONRIVER = "SUSHISWAP_MOONRIVER";
    export const SUSHISWAP_XDAI = "SUSHISWAP_XDAI";
    export const UNISWAP_V2_MAINNET = "UNISWAP_V2_MAINNET";
  }