export enum ConfigurationFields {
    NETWORK = "NETWORK",
  
    PROTOCOL_NAME = "PROTOCOL_NAME",
    PROTOCOL_SLUG = "PROTOCOL_SLUG",
  
    FACTORY_ADDRESS  = "FACTORY_ADDRESS",
  
    TRADING_FEE = "TRADING_FEE",
    PROTOCOL_FEE_TO_ON  = "PROTOCOL_FEE_TO_ON",
    LP_FEE_TO_ON = "LP_FEE_TO_ON",
    PROTOCOL_FEE_TO_OFF = "PROTOCOL_FEE_TO_OFF",
    LP_FEE_TO_OFF = "LP_FEE_TO_OFF",
    FEE_ON_OFF = "FEE_ON_OFF",
  
    REWARD_INTERVAL_TYPE = "REWARD_INTERVAL_TYPE",
  
    REFERENCE_TOKEN = "NATIVE_TOKEN",
    REWARD_TOKENS = "REWARD_TOKENS",
    WHITELIST_TOKENS = "WHITELIST_TOKENS",
    STABLE_COINS = "STABLE_COINS",
    STABLE_ORACLE_POOLS = "STABLE_ORACLE_POOLS",
    UNTRACKED_PAIRS = "UNTRACKED_PAIRS"
  }