specVersion: 0.0.2
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: Factory
    network: {{network}}
    source:
      address: "{{address}}"
      abi: Factory
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Factory
          file: ./abis/trader-joe/Factory.json
        - name: TokenABI
          file: ./abis/trader-joe/ERC20.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/mappings/factory.ts
  - kind: ethereum
    name: MasterChefV2
    network: {{network}}
    source:
      address: "{{MasterChefV2Address}}"
      abi: MasterChefV2TraderJoe
      startBlock: {{MasterChefV2StartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: MasterChefV2TraderJoe
          file: ./abis/trader-joe/MasterChefV2TraderJoe.json
        - name: TokenABI
          file: ./abis/trader-joe/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256)
          handler: handleWithdraw
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256)
          handler: handleEmergencyWithdraw
        - event: Add(indexed uint256,uint256,indexed address,indexed address)
          handler: handleAdd
        - event: Set(indexed uint256,uint256,indexed address,bool)
          handler: handleSet
        - event: UpdateEmissionRate(indexed address,uint256)
          handler: handleUpdateEmissionRate
      file: ./protocols/trader-joe/src/mappings/masterchef/rewardV2.ts
  - kind: ethereum
    name: MasterChefV3
    network: {{network}}
    source:
      address: "{{MasterChefV3Address}}"
      abi: MasterChefV3TraderJoe
      startBlock: {{MasterChefV3StartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: MasterChefV3TraderJoe
          file: ./abis/trader-joe/MasterChefV3TraderJoe.json
        - name: TokenABI
          file: ./abis/trader-joe/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256)
          handler: handleDepositV3
        - event: Withdraw(indexed address,indexed uint256,uint256)
          handler: handleWithdrawV3
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256)
          handler: handleEmergencyWithdrawV3
        - event: Add(indexed uint256,uint256,indexed address,indexed address)
          handler: handleAdd
        - event: Set(indexed uint256,uint256,indexed address,bool)
          handler: handleSet
      file: ./protocols/trader-joe/src/mappings/masterchef/rewardV3.ts
templates:
  - kind: ethereum/contract
    name: Pair
    network: {{network}}
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities: []
      abis:
        - name: Pair
          file: ./abis/spiritswap/Pair.json
        - name: Factory
          file: ./abis/spiritswap/Factory.json
        - name: TokenABI
          file: ./abis/spiritswap/ERC20.json
      eventHandlers:
        - event: Mint(indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,uint256,uint256,indexed address)
          handler: handleBurn
        - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync