specVersion: 0.0.5
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: Configurator
    network: {{ network }}
    source:
      address: "{{ factoryAddress }}"
      abi: Configurator
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/compound-v3/src/mapping.ts
      entities: []
      abis:
        - name: Configurator
          file: ./abis/Configurator.json
        - name: Comet
          file: ./abis/Comet.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
      eventHandlers:
        - event: CometDeployed(indexed address,indexed address)
          handler: handleCometDeployed
templates:
  - name: Comet
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: Comet
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/compound-v3/src/mapping.ts
      entities: []
      abis:
        - name: Comet
          file: ./abis/Comet.json
      eventHandlers:
        - event: Supply(indexed address,indexed address,uint256)
          handler: handleSupply
          receipt: true
        - event: SupplyCollateral(indexed address,indexed address,indexed address,uint256)
          handler: handleSupplyCollateral
          receipt: true
        - event: Withdraw(indexed address,indexed address,uint256)
          handler: handleWithdraw
          receipt: true
        - event: WithdrawCollateral(indexed address,indexed address,indexed address,uint256)
          handler: handleWithdrawCollateral
          receipt: true
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        # - event: AbsorbCollateral(indexed address,indexed address,indexed address,uint256,uint256)
        #   handler: handleAbsorbCollateral
        # - event: AbsorbDebt()
