specVersion: 1.0.0
schema:
  file: ./schema.graphql
indexerHints:
  prune: auto
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: FusePoolDirectory
    network: {{ network }}
    source:
      address: "{{ fusePoolDirectoryAddress }}"
      abi: FusePoolDirectory
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Market
      abis:
        - name: FusePoolDirectory
          file: ./abis/rari-fuse/FusePoolDirectory.json
        - name: Comptroller
          file: ./abis/Comptroller.json
      eventHandlers:
        - event: PoolRegistered(uint256,(string,address,address,uint256,uint256))
          handler: handlePoolRegistered
      file: ./protocols/rari-fuse/src/mappings.ts
templates:
  - name: Comptroller
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: Comptroller
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/rari-fuse/src/mappings.ts
      entities:
        - LendingProtocol
        - Market
        - Token
      abis:
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: CToken
          file: ./abis/rari-fuse/CToken.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: MarketListed(address)
          handler: handleMarketListed
        - event: MarketEntered(address,address)
          handler: handleMarketEntered
        - event: MarketExited(address,address)
          handler: handleMarketExited
        - event: NewCollateralFactor(address,uint256,uint256)
          handler: handleNewCollateralFactor
        - event: NewLiquidationIncentive(uint256,uint256)
          handler: handleNewLiquidationIncentive
        - event: NewPriceOracle(address,address)
          handler: handleNewPriceOracle
        - event: ActionPaused(address,string,bool)
          handler: handleActionPaused
  - name: CToken
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: CToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/rari-fuse/src/mappings.ts
      entities:
        - Event
        - Market
        - UsageMetricsDailySnapshot
        - FinancialsDailySnapshot
        - MarketDailySnapshot
      abis:
        - name: FuseComptroller
          file: ./abis/rari-fuse/FuseComptroller.json
        - name: RewardsDistributorDelegator
          file: ./abis/rari-fuse/RewardsDistributorDelegator.json
        - name: CToken
          file: ./abis/rari-fuse/CToken.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Mint(address,uint256,uint256)
          handler: handleMint
        - event: Redeem(address,uint256,uint256)
          handler: handleRedeem
        - event: Borrow(address,uint256,uint256,uint256)
          handler: handleBorrow
        - event: RepayBorrow(address,address,uint256,uint256,uint256)
          handler: handleRepayBorrow
        - event: LiquidateBorrow(address,address,uint256,address,uint256)
          handler: handleLiquidateBorrow
        - event: AccrueInterest(uint256,uint256,uint256,uint256)
          handler: handleAccrueInterest
        - event: NewReserveFactor(uint256,uint256)
          handler: handleNewReserveFactor
        - event: NewFuseFee(uint256,uint256)
          handler: handleNewFuseFee
        - event: NewAdminFee(uint256,uint256)
          handler: handleNewAdminFee
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
