specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{ /graftEnabled }}
dataSources:
  - kind: ethereum
    network: {{ network }}
    name: LRTConfig
    source:
      address: "{{ LRTConfig.address }}"
      abi: LRTConfig
      startBlock: {{ LRTConfig.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: LRTConfig
          file: ./abis/LRTConfig.json
        - name: LRTDepositPool
          file: ./abis/LRTDepositPool.json
        - name: LRT
          file: ./abis/LRT.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: AddedNewSupportedAsset(indexed address,uint256)
          handler: handleAddedNewSupportedAsset
      file: ./src/mappings/lrtConfigMappings.ts
  - kind: ethereum
    network: {{ network }}
    name: LRTDepositPool
    source:
      address: "{{ LRTDepositPool.address }}"
      abi: LRTDepositPool
      startBlock: {{ LRTDepositPool.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: LRTDepositPool
          file: ./abis/LRTDepositPool.json
        - name: LRTConfig
          file: ./abis/LRTConfig.json
        - name: LRT
          file: ./abis/LRT.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: AssetDeposit(indexed address,indexed address,uint256,uint256,string)
          handler: handleAssetDeposit
        - event: AssetSwapped(indexed address,indexed address,uint256,uint256)
          handler: handleAssetSwapped
        - event: WithdrawalClaimed(indexed address,indexed address,uint256)
          handler: handleWithdrawalClaimed
      file: ./src/mappings/lrtDepositPoolMappings.ts
