specVersion: 0.0.2
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: Factory
    network: {{network}}
    source:
      address: "{{factory.address}}"
      abi: Factory
      startBlock: {{factory.startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Factory
          file: ./abis/pangolin/Factory.json
        - name: TokenABI
          file: ./abis/pangolin/ERC20.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/mappings/factory.ts
  - kind: ethereum
    name: MiniChef
    network: {{network}}
    source:
      address: "{{miniChefAddress}}"
      abi: MiniChefV2
      startBlock: {{miniChefStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: MiniChefV2
          file: ./abis/pangolin/MiniChefV2.json
        - name: Factory
          file: ./abis/pangolin/Factory.json
        - name: TokenABI
          file: ./abis/pangolin/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256,indexed address)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleWithdraw
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleEmergencyWithdraw
        - event: PoolSet(indexed uint256,uint256,indexed address,bool)
          handler: handlePoolSet
        - event: PoolAdded(indexed uint256,uint256,indexed address,indexed address)
          handler: handlePoolAdded
        - event: LogRewardPerSecond(uint256)
          handler: handleLogRewardPerSecond
      file: ./protocols/pangolin/src/mappings/masterchef/rewardMini.ts
templates:
  - kind: ethereum/contract
    name: Pair
    network: {{network}}
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities: []
      abis:
        - name: Pair
          file: ./abis/pangolin/Pair.json
        - name: Factory
          file: ./abis/pangolin/Factory.json
        - name: TokenABI
          file: ./abis/pangolin/ERC20.json
      eventHandlers:
        - event: Mint(indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,uint256,uint256,indexed address)
          handler: handleBurn
        - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync