specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: near
    name: Contract
    network: {{ chain }}
    source:
      account: "{{ contract }}"
      startBlock: {{ startBlock }}
    mapping:
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      receiptHandlers:
        - handler: handleReceipt
      file: ./src/index.ts