specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Comptroller
    network: {{ network }}
    source:
      address: "{{ factoryAddress }}"
      abi: Comptroller
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Protocol
        - Market
        - Token
      abis:
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: CToken
          file: ./abis/CToken.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: MarketListed(address)
          handler: handleMarketListed
        - event: MarketEntered(address,address)
          handler: handleMarketEntered
        - event: MarketExited(address,address)
          handler: handleMarketExited
        - event: NewPriceOracle(address,address)
          handler: handleNewPriceOracle
        - event: NewCollateralFactor(address,uint256,uint256)
          handler: handleNewCollateralFactor
        - event: NewLiquidationIncentive(uint256,uint256)
          handler: handleNewLiquidationIncentive
        - event: ActionPaused(address,string,bool)
          handler: handleActionPaused
      file: ./protocols/iron-bank/src/mapping.ts

  - kind: ethereum/contract
    name: StakingRewardsFactory
    network: {{ network }}
    source:
      address: "{{ rewardsFactoryAddress }}"
      abi: StakingRewardsFactory
      startBlock: {{ rewardStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: StakingRewardsFactory
          file: ./abis/iron-bank/StakingRewardsFactory.json
        - name: StakingRewards
          file: ./abis/iron-bank/StakingRewards.json
      eventHandlers:
        - event: StakingRewardsCreated(indexed address,indexed address)
          handler: handleStakingRewardsCreated
      file: ./protocols/iron-bank/src/mapping.ts        

templates:
  - name: CToken
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: CToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Deposit
        - Withdraw
        - Borrow
        - Repay
        - Liquidate
      abis:
        - name: CToken
          file: ./abis/CToken.json
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: Mint(address,uint256,uint256)
          handler: handleMint
        - event: Redeem(address,uint256,uint256)
          handler: handleRedeem
        - event: Borrow(address,uint256,uint256,uint256)
          handler: handleBorrow
        - event: RepayBorrow(address,address,uint256,uint256,uint256)
          handler: handleRepayBorrow
        - event: LiquidateBorrow(address,address,uint256,address,uint256)
          handler: handleLiquidateBorrow
        - event: AccrueInterest(uint256,uint256,uint256,uint256)
          handler: handleAccrueInterest
        - event: NewReserveFactor(uint256,uint256)
          handler: handleNewReserveFactor
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/iron-bank/src/mapping.ts

  - name: StakingRewards
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: StakingRewards
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Market
      abis:
        - name: StakingRewards
          file: ./abis/iron-bank/StakingRewards.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: BeethovenXPool
          file: ./abis/iron-bank/BeethovenXPool.json
        - name: BeethovenXVault
          file: ./abis/iron-bank/BeethovenXVault.json
      eventHandlers:
        - event: RewardPaid(indexed address,address,uint256)
          handler: handleRewardPaid
        - event: Staked(indexed address,uint256)
          handler: handleStaked
        - event: Withdrawn(indexed address,uint256)
          handler: handleWithdrawn
      file: ./protocols/iron-bank/src/mapping.ts

