specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{ #graftEnabled }}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{ /graftEnabled }}
dataSources:
  {{ #ConcentratorCvxCRV }}
  - kind: ethereum
    network: {{ network }}
    name: {{ name }}
    source:
      address: "{{ address }}"
      abi: ConcentratorCvxCRV
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: ConcentratorCvxCRV
          file: ./abis/ConcentratorCvxCRV.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,indexed address,uint256)
          handler: handleDepositWithoutShares
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,uint256,uint8)
          handler: handleWithdrawWithOption
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: Harvest(indexed address,uint256)
          handler: handleHarvestWithOnlyAmount
        - event: Harvest(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleHarvest
      file: ./src/mappings/concentratorCvxCRVMappings.ts
  {{ /ConcentratorCvxCRV }}

  {{ #AladdinConvexVault }}
  - kind: ethereum
    network: {{ network }}
    name: {{ name }}
    source:
      address: "{{ address }}"
      abi: AladdinConvexVault
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: AladdinConvexVault
          file: ./abis/AladdinConvexVault.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed uint256,indexed address,uint256)
          handler: handleDeposit
        - event: Deposit(indexed uint256,indexed address,indexed address,uint256,uint256)
          handler: handleDepositWithShares
        - event: Withdraw(indexed uint256,indexed address,uint256)
          handler: handleWithdraw
        - event: Withdraw(indexed uint256,indexed address,indexed address,address,uint256,uint256)
          handler: handleWithdrawWithShares
        - event: Harvest(indexed address,uint256,uint256,uint256)
          handler: handleHarvest
        - event: Harvest(indexed uint256,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleHarvestWithCaller
      file: ./src/mappings/aladdinConvexVaultMappings.ts
  {{ /AladdinConvexVault }}

