specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  {{#HubPool}}
  - kind: ethereum
    name: HubPool
    network: mainnet
    source:
      address: "0xc186fa914353c44b2e33ebe05f21846f1048beda"
      abi: HubPool
      startBlock: 14819537
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LiquidityAdded
        - LiquidityRemoved
      abis:
        - name: HubPool
          file: ./abis/HubPool.json
        ################################################ 
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: LiquidityAdded(indexed address,uint256,uint256,indexed address)
          handler: handleLiquidityAdded
        - event: LiquidityRemoved(indexed address,uint256,uint256,indexed address)
          handler: handleLiquidityRemoved
      file: ./src/handlers/liquidity.ts
  {{/HubPool}}
  {{#AcceleratingDistributor}}
  - kind: ethereum
    name: AcceleratingDistributor
    network: mainnet
    source:
      address: "0x9040e41eF5E8b281535a96D9a48aCb8cfaBD9a48"
      abi: AcceleratingDistributor
      startBlock: 15977129
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Token
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
      abis:
        - name: AcceleratingDistributor
          file: ./abis/AcceleratingDistributor.json
        ################################################ 
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Stake(indexed address,indexed address,uint256,uint256,uint256,uint256)
          handler: handleStake
        - event: Unstake(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleUnstake
      file: ./src/handlers/staking.ts
  {{/AcceleratingDistributor}}
  {{#SpokePool}}
  - kind: ethereum
    name: {{ name }}
    network: {{ network }}
    source:
      address: "{{ address }}"
      abi: {{ name }}
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - BridgeProtocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
        - Token
        - CrosschainToken
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - PoolRoute
        - PoolRouteSnapshot   
      abis:
        - name: SpokePool1
          file: ./abis/SpokePool1.json
        - name: SpokePool2
          file: ./abis/SpokePool2.json
        - name: AcceleratingDistributor
          file: ./abis/AcceleratingDistributor.json
        ################################################ 
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: {{ filledRelayEvent }}
          handler: handleFilledRelay{{ name }}
        - event: {{ fundsDepositedEvent }}
          handler: handleFundsDeposited{{ name }}
      file: ./src/handlers/transfersSpokePool.ts
  {{/SpokePool}}