specVersion: 0.0.8
schema:
  file: ./schema.graphql
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{ subgraphId }} # Subgraph ID of base subgraph
  block: {{ graftStartBlock }} # Block number
{{ /graftEnabled }}
dataSources:
  - kind: ethereum
    network: {{ network }}
    name: EigenConfig
    source:
      address: "{{ EigenConfig.address }}"
      abi: EigenConfig
      startBlock: {{ EigenConfig.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: EigenConfig
          file: ./abis/EigenConfig.json
        - name: EigenStaking
          file: ./abis/EigenStaking.json
        - name: MLRT
          file: ./abis/MLRT.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: AddedNewSupportedAsset(indexed address,indexed address,uint256)
          handler: handleAddedNewSupportedAsset
        - event: ReceiptTokenUpdated(indexed address,indexed address)
          handler: handleReceiptTokenUpdated
      file: ./src/mappings/eigenConfigMappings.ts
  - kind: ethereum
    network: {{ network }}
    name: EigenStaking
    source:
      address: "{{ EigenStaking.address }}"
      abi: EigenStaking
      startBlock: {{ EigenStaking.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: EigenStaking
          file: ./abis/EigenStaking.json
        - name: EigenConfig
          file: ./abis/EigenConfig.json
        - name: MLRT
          file: ./abis/MLRT.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: AssetDeposit(indexed address,indexed address,uint256,indexed address,uint256,bool)
          handler: handleAssetDeposit
        - event: AssetDeposit(indexed address,indexed address,uint256,indexed address)
          handler: handleAssetDepositWithoutMintAmount
      file: ./src/mappings/eigenStakingMappings.ts
