specVersion: 0.0.2
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
features: 
  - grafting
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: Factory
    network: {{network}}
    source:
      address: "{{address}}"
      abi: Factory
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Factory
          file: ./abis/ubeswap/Factory.json
        - name: TokenABI
          file: ./abis/ubeswap/ERC20.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/mappings/factory.ts
  - kind: ethereum
    name: PoolManager
    network: {{network}}
    source:
      address: "{{poolManagerAddress}}"
      abi: PoolManager
      startBlock: {{poolManagerStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: PoolManager
          file: ./abis/ubeswap/PoolManager.json
        - name: StakingRewards
          file: ./abis/ubeswap/StakingRewards.json
        - name: TokenABI
          file: ./abis/ubeswap/ERC20.json
        - name: UniswapV2Pair
          file: ./abis/ubeswap/UniswapV2Pair.json
      eventHandlers:
        - event: UpdatePoolWeight(indexed address,indexed uint256,uint256,indexed bool)
          handler: handleUpdatePoolWeight
      file: ./protocols/ubeswap/src/mappings/stakingrewards/handlePoolCreation.ts
templates:
  - kind: ethereum/contract
    name: Pair
    network: {{network}}
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities: []
      abis:
        - name: Pair
          file: ./abis/ubeswap/Pair.json
        - name: Factory
          file: ./abis/ubeswap/Factory.json
        - name: TokenABI
          file: ./abis/ubeswap/ERC20.json
      eventHandlers:
        - event: Mint(indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,uint256,uint256,indexed address)
          handler: handleBurn
        - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync
  - kind: ethereum/contract
    name: StakingRewards
    network: {{network}}
    source:
      abi: StakingRewards
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/ubeswap/src/mappings/stakingrewards/handleReward.ts
      entities: []
      abis:
        - name: StakingRewards
          file: ./abis/ubeswap/StakingRewards.json
        - name: PoolManager
          file: ./abis/ubeswap/PoolManager.json
        - name: TokenABI
          file: ./abis/ubeswap/ERC20.json
        - name: UniswapV2Pair
          file: ./abis/ubeswap/UniswapV2Pair.json
          
      eventHandlers:
        - event: Staked(indexed address,uint256)
          handler: handleStaked
        - event: Withdrawn(indexed address,uint256)
          handler: handleWithdrawn
        - event: RewardPaid(indexed address,uint256)
          handler: handleRewardPaid
