specVersion: 0.0.2
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
features: 
  - grafting
{{/graftEnabled}}
dataSources:
  - kind: ethereum
    name: Factory
    network: mainnet
    source:
      address: "0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac"
      abi: Factory
      startBlock: 10794229
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Factory
          file: ./abis/sushiswap/Factory.json
        - name: TokenABI
          file: ./abis/sushiswap/ERC20.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/mappings/factory.ts
  - kind: ethereum
    name: MasterChef
    network: mainnet
    source:
      address: "0xc2edad668740f1aa35e4d8f227fb8e17dca888cd"
      abi: MasterChefSushiswap
      startBlock: 10794230
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: MasterChefSushiswap
          file: ./abis/sushiswap/MasterChefSushiswap.json
        - name: TokenABI
          file: ./abis/sushiswap/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256)
          handler: handleWithdraw
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256)
          handler: handleEmergencyWithdraw
      file: ./protocols/sushiswap/src/mappings/masterchef/reward.ts

  - kind: ethereum
    name: MasterChefV2
    network: mainnet
    source:
      address: "0xef0881ec094552b2e128cf945ef17a6752b4ec5d"
      abi: MasterChefV2Sushiswap
      startBlock: 12428169
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: MasterChefV2Sushiswap
          file: ./abis/sushiswap/MasterChefV2Sushiswap.json
        - name: TokenABI
          file: ./abis/sushiswap/ERC20.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256,indexed address)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleWithdraw
        - event: EmergencyWithdraw(indexed address,indexed uint256,uint256,indexed address)
          handler: handleEmergencyWithdraw
        - event: LogSetPool(indexed uint256,uint256,indexed address,bool)
          handler: handleLogSetPool
        - event: LogPoolAddition(indexed uint256,uint256,indexed address,indexed address)
          handler: handleLogPoolAddition
      file: ./protocols/sushiswap/src/mappings/masterchef/rewardV2.ts
templates:
  - kind: ethereum/contract
    name: Pair
    network: mainnet
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities: []
      abis:
        - name: Pair
          file: ./abis/sushiswap/Pair.json
        - name: Factory
          file: ./abis/sushiswap/Factory.json
        - name: TokenABI
          file: ./abis/sushiswap/ERC20.json
      eventHandlers:
        - event: Mint(indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,uint256,uint256,indexed address)
          handler: handleBurn
        - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync