specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
features: 
  - grafting
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: Factory
    network: {{network}}
    source:
      address: "{{factory.address}}"
      abi: Factory
      startBlock: {{factory.startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/factory.ts
      entities:
        - Token
        - DexAmmProtocol
        - LiquidityPool
        - LiquidityPoolFee
        - Protocol
      abis:
        - name: Factory
          file: ./abis/uniswap-v2/Factory.json
        - name: TokenABI
          file: ./abis/uniswap-v2/ERC20.json
        
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Factory/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Factory/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Factory/Pair.json
        
        - name: CalculationsSushiswap
          file: ./abis/Prices/Calculations/SushiSwap.json

      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      ##callHandlers:
        ##- function: setFeeTo(address)
          ##handler: handleFeeTo
templates:
  - kind: ethereum/contract
    name: Pair
    network: {{network}}
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities:
        - LiqudityPool
        - Token
        - Deposit
        - Withdraw
        - Swap
        - LiquidityPool
        - LiquidityPoolFee
        - DexAmmProtocol
        - Token
        - _Transaction
        - _Mint
        - _Burn
        - _PricesUSD
        - UsageMetricsDailySnapshot
        - FinancialsDailySnapshot
        - _Account
        - _DailyActiveAccount
        - PoolDailySnapshot
        - _TokenTracker
      abis:
        - name: Pair
          file: ./abis/uniswap-v2/Pair.json
        - name: Factory
          file: ./abis/uniswap-v2/Factory.json
        - name: TokenABI
          file: ./abis/uniswap-v2/ERC20.json
        
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Factory/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Factory/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Factory/Pair.json
        
        - name: CalculationsSushiswap
          file: ./abis/Prices/Calculations/SushiSwap.json

      eventHandlers:
        - event: Mint(indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,uint256,uint256,indexed address)
          handler: handleBurn
        - event: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint112,uint112)
          handler: handleSync
          