specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Comptroller
    network: {{ network }}
    source:
      address: "{{ factoryAddress }}"
      abi: Comptroller
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Protocol
        - Market
        - Token
      abis:
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: CToken
          file: ./abis/aurigami/CToken.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: MarketListed(address)
          handler: handleMarketListed
        - event: MarketEntered(address,address)
          handler: handleMarketEntered
        - event: MarketExited(address,address)
          handler: handleMarketExited
        - event: NewPriceOracle(address,address)
          handler: handleNewPriceOracle
        - event: NewCollateralFactor(address,uint256,uint256)
          handler: handleNewCollateralFactor
        - event: NewLiquidationIncentive(uint256,uint256)
          handler: handleNewLiquidationIncentive
        - event: ActionPaused(address,string,bool)
          handler: handleActionPaused
      file: ./protocols/aurigami/src/mapping.ts
templates:
  - name: CToken
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: CToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Deposit
        - Withdraw
        - Borrow
        - Repay
        - Liquidate
      abis:
        - name: CToken
          file: ./abis/aurigami/CToken.json
        - name: Comptroller
          file: ./abis/Comptroller.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/prices-new/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/prices-new/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/prices-new/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/prices-new/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/prices-new/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/prices-new/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/prices-new/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/prices-new/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/prices-new/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/prices-new/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/prices-new/Uniswap/Pair.json
      eventHandlers:
        - event: Mint(address,uint256,uint256)
          handler: handleMint
        - event: Redeem(address,uint256,uint256)
          handler: handleRedeem
        - event: Borrow(address,uint256,uint256,uint256)
          handler: handleBorrow
        - event: RepayBorrow(address,address,uint256,uint256,uint256)
          handler: handleRepayBorrow
        - event: LiquidateBorrow(address,address,uint256,address,uint256)
          handler: handleLiquidateBorrow
        - event: AccrueInterest(uint256,uint256,uint256,uint256)
          handler: handleAccrueInterest
        - event: NewReserveFactor(uint256,uint256)
          handler: handleNewReserveFactor
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/aurigami/src/mapping.ts
