specVersion: 0.0.4
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  {{#lpStaking}}
  - kind: ethereum
    name: {{ name }}
    network: {{ network }}
    source:
      address: "{{ address }}"
      abi: {{ abi }}
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - BridgeProtocol
      abis:
        - name: Bridge
          file: ./abis/Stargate/Bridge.json
        - name: LPStaking
          file: ./abis/Stargate/LPStaking.json
        - name: LPStakingTime
          file: ./abis/Stargate/LPStakingTime.json
        - name: Pool
          file: ./abis/Stargate/Pool.json
        - name: Router
          file: ./abis/Stargate/Router.json
        - name: Factory
          file: ./abis/Stargate/Factory.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256)
          handler: {{ depositHandler }}
        - event: Withdraw(indexed address,indexed uint256,uint256)
          handler: {{ withdrawHandler }}
      file: {{{ file }}}
  {{/lpStaking}}
templates:
  - name: PoolTemplate
    kind: ethereum
    network: {{ network }}
    source:
      abi: Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - BridgeProtocol
      abis:
        - name: Bridge
          file: ./abis/Stargate/Bridge.json
        - name: LPStaking
          file: ./abis/Stargate/LPStaking.json
        - name: LPStakingTime
          file: ./abis/Stargate/LPStakingTime.json
        - name: Pool
          file: ./abis/Stargate/Pool.json
        - name: Router
          file: ./abis/Stargate/Router.json
        - name: Factory
          file: ./abis/Stargate/Factory.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Swap(uint16,uint256,address,uint256,uint256,uint256,uint256,uint256)
          handler: handleSwapOut
        - event: SwapRemote(address,uint256,uint256,uint256)
          handler: handleSwapIn
          receipt: true
        - event: Mint(address,uint256,uint256,uint256)
          handler: handleMint
        - event: Burn(address,uint256,uint256)
          handler: handleBurn
      file: {{{ file }}}
