{
  protocols {
    borrowerPermissionType
    collateralizationType
    cumulativeProtocolSideRevenueUSD
    cumulativeSupplySideRevenueUSD
    cumulativeTotalRevenueUSD
    cumulativeUniqueUsers
    id
    lenderPermissionType
    lendingType
    methodologyVersion
    name
    network
    poolCreatorPermissionType
    protocol
    protocolControlledValueUSD
    riskType
    schemaVersion
    slug
    subgraphVersion
    totalPoolCount
    totalValueLockedUSD
    type
    ... on LendingProtocol {
      borrowCount
      borrowerPermissionType
      collateralizationType
      cumulativeBorrowUSD
      cumulativeDepositUSD
      cumulativeLiquidateUSD
      cumulativePositionCount
      cumulativeProtocolSideRevenueUSD
      cumulativeSupplySideRevenueUSD
      cumulativeTotalRevenueUSD
      cumulativeUniqueBorrowers
      cumulativeUniqueDepositors
      cumulativeUniqueLiquidatees
      cumulativeUniqueLiquidators
      cumulativeUniqueUsers
      depositCount
      flashloanCount
      id
      lenderPermissionType
      lendingType
      liquidationCount
      methodologyVersion
      mintedTokenSupplies
      name
      network
      openPositionCount
      poolCreatorPermissionType
      protocol
      protocolControlledValueUSD
      repayCount
      rewardTokenEmissionsAmount
      rewardTokenEmissionsUSD
      riskType
      schemaVersion
      slug
      subgraphVersion
      totalBorrowBalanceUSD
      totalDepositBalanceUSD
      totalPoolCount
      totalValueLockedUSD
      transactionCount
      transferCount
      type
      withdrawCount
    }
  }
  tokens {
    decimals
    id
    lastPriceBlockNumber
    lastPriceUSD
    name
    symbol
    type
  }
  accounts {
    borrowCount
    closedPositionCount
    depositCount
    flashloanCount
    id
    liquidateCount
    liquidationCount
    openPositionCount
    positionCount
    receivedCount
    repayCount
    rewardsClaimedUSD
    transferredCount
    withdrawCount
  }
  positions {
    balance
    blockNumberClosed
    blockNumberOpened
    borrowCount
    depositCount
    hashClosed
    hashOpened
    id
    isCollateral
    isIsolated
    liquidationCount
    receivedCount
    repayCount
    side
    timestampClosed
    timestampOpened
    transferredCount
    type
    withdrawCount
  }
  flashloans {
    amount
    amountUSD
    blockNumber
    feeAmount
    feeAmountUSD
    gasLimit
    gasPrice
    gasUsed
    hash
    id
    logIndex
    nonce
    timestamp
  }
  liquidates {
    amount
    amountUSD
    blockNumber
    gasLimit
    gasPrice
    gasUsed
    hash
    id
    logIndex
    nonce
    profitUSD
    timestamp
  }
}
