specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: GovernorBeta
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: GovernorBeta
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: GovernorBeta
          file: ./abis/cryptex-governance/GovernorBeta.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
          handler: handleProposalCreated
        - event: ProposalExecuted(uint256)
          handler: handleProposalExecuted
        - event: ProposalQueued(uint256,uint256)
          handler: handleProposalQueued
        - event: VoteCast(address,uint256,bool,uint256)
          handler: handleVoteCast
      file: ./protocols/cryptex-governance/src/GovernorBeta.ts
  - kind: ethereum/contract
    name: Ctx
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: Ctx
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: Ctx
          file: ./abis/cryptex-governance/Ctx.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,indexed address)
          handler: handleDelegateChanged
        - event: DelegateVotesChanged(indexed address,uint256,uint256)
          handler: handleDelegateVotesChanged
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/cryptex-governance/src/Ctx.ts
      