specVersion: 0.0.4
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: TroveManager
    network: mainnet
    source:
      address: "0xA39739EF8b0231DbFA0DcdA07d7e29faAbCf4bb2"
      abi: TroveManager
      startBlock: 12178557
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: TroveManager
          file: ./abis/TroveManager.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: TroveUpdated(indexed address,uint256,uint256,uint256,uint8)
          handler: handleTroveUpdated
        - event: Redemption(uint256,uint256,uint256,uint256)
          handler: handleRedemption
        - event: TroveLiquidated(indexed address,uint256,uint256,uint8)
          handler: handleTroveLiquidated
        - event: Liquidation(uint256,uint256,uint256,uint256)
          handler: handleLiquidation
          receipt: true
      file: ./src/mapping/TroveManager.ts
  - kind: ethereum/contract
    name: BorrowerOperations
    network: mainnet
    source:
      address: "0x24179CD81c9e782A4096035f7eC97fB8B783e007"
      abi: BorrowerOperations
      startBlock: 12178582
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: BorrowerOperations
          file: ./abis/BorrowerOperations.json
      eventHandlers:
        - event: LUSDBorrowingFeePaid(indexed address,uint256)
          handler: handleLUSDBorrowingFeePaid
        - event: TroveUpdated(indexed address,uint256,uint256,uint256,uint8)
          handler: handleTroveUpdated
      file: ./src/mapping/BorrowerOperations.ts
  - name: PriceFeed
    kind: ethereum/contract
    network: mainnet
    source:
      abi: PriceFeed
      address: "0x4c517D4e2C851CA76d7eC94B805269Df0f2201De"
      startBlock: 12178551
    mapping:
      file: ./src/mapping/PriceFeed.ts
      language: wasm/assemblyscript
      kind: ethereum/events
      apiVersion: 0.0.7
      entities:
        - Token
      abis:
        - name: PriceFeed
          file: ./abis/PriceFeed.json
      eventHandlers:
        - event: LastGoodPriceUpdated(uint256)
          handler: handleLastGoodPriceUpdated
  - kind: ethereum/contract
    name: ActivePool
    network: mainnet
    source:
      address: "0xDf9Eb223bAFBE5c5271415C75aeCD68C21fE3D7F"
      abi: ActivePool
      startBlock: 12178562
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ActivePool
          file: ./abis/ActivePool.json
      eventHandlers:
        - event: ActivePoolETHBalanceUpdated(uint256)
          handler: handleActivePoolETHBalanceUpdated
        - event: ActivePoolLUSDDebtUpdated(uint256)
          handler: handleActivePoolLUSDDebtUpdated
      file: ./src/mapping/ActivePool.ts
  - kind: ethereum/contract
    name: CollSurplusPool
    network: mainnet
    source:
      address: "0x3D32e8b97Ed5881324241Cf03b2DA5E2EBcE5521"
      abi: CollSurplusPool
      startBlock: 12178578
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: CollSurplusPool
          file: ./abis/CollSurplusPool.json
      eventHandlers:
        - event: CollBalanceUpdated(indexed address,uint256)
          handler: handleCollBalanceUpdated
      file: ./src/mapping/CollSurplusPool.ts
  - kind: ethereum/contract
    name: StabilityPool
    network: mainnet
    source:
      address: "0x66017D22b0f8556afDd19FC67041899Eb65a21bb"
      abi: StabilityPool
      startBlock: 12178565
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: StabilityPool
          file: ./abis/StabilityPool.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: StabilityPoolETHBalanceUpdated(uint256)
          handler: handleStabilityPoolETHBalanceUpdated
        - event: StabilityPoolLUSDBalanceUpdated(uint256)
          handler: handleStabilityPoolLUSDBalanceUpdated
        - event: ETHGainWithdrawn(indexed address,uint256,uint256)
          handler: handleETHGainWithdrawn
        - event: UserDepositChanged(indexed address,uint256)
          handler: handleUserDepositChanged
      file: ./src/mapping/StabilityPool.ts
