specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Controller
    network: {{ network }}
    source:
      address: '0x222412af183bceadefd72e4cb1b71f1889953b1c'
      startBlock: 10770087
      abi: ControllerContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
        - YieldAggregator
        - Token
      abis:
        - name: ControllerContract
          file: ./abis/Controller.json
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
      callHandlers:
        - function: addVaultAndStrategy(address,address)
          handler: handleAddVaultAndStrategy
      file: ./src/controller.ts
templates:
  - kind: ethereum/contract
    name: Vault
    network: {{ network }}
    source:
      abi: VaultContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
      abis:
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
      eventHandlers:
        - event: Deposit(indexed address,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256)
          handler: handleWithdraw
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./src/vault.ts
