specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Controller
    network: {{ network }}
    source:
      address: '0x222412af183bceadefd72e4cb1b71f1889953b1c'
      startBlock: 10770087
      abi: ControllerContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
        - YieldAggregator
        - Token
      abis:
        - name: ControllerContract
          file: ./abis/Controller.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
        - name: UniswapPairContract
          file: ./abis/UniswapV2Pair.json
      callHandlers:
        - function: addVaultAndStrategy(address,address)
          handler: handleAddVaultAndStrategy
      eventHandlers:
        - event: SharePriceChangeLog(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleSharePriceChangeLog
      file: ./src/controller.ts

  - kind: ethereum
    name: ControllerV2
    network: {{ network }}
    source:
      address: '0x3cC47874dC50D98425ec79e647d83495637C55e3'
      startBlock: 12652884
      abi: ControllerContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
        - YieldAggregator
        - Token
      abis:
        - name: ControllerContract
          file: ./abis/Controller.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
        - name: UniswapPairContract
          file: ./abis/UniswapV2Pair.json
      eventHandlers:
        - event: SharePriceChangeLog(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleSharePriceChangeLog
      file: ./src/controller.ts

  - kind: ethereum
    name: NotifyHelper
    network: {{ network }}
    source:
      address: '0xe20c31e3d08027f5aface84a3a46b7b3b165053c'
      startBlock: 11276997
      abi: NotifyHelper
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
        - RewardToken
        - Token
      abis:
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: NotifyHelper
          file: ./abis/NotifyHelper.json
        - name: NoMintRewardPool
          file: ./abis/NoMintRewardPool.json
      callHandlers:
        - function: notifyPools(uint256[],address[],uint256)
          handler: handleNotifyPools
        - function: notifyPoolsIncludingProfitShare(uint256[],address[],uint256,uint256,uint256)
          handler: handleNotifyPoolsIncludingProfitShare
      file: ./src/notifyHelper.ts

  - kind: ethereum
    name: MegaFactory
    network: {{ network }}
    source:
      address: '0xe1ec9151eb8d9a3451b8f623ce8b62632a6d4f4d'
      startBlock: 13658254
      abi: MegaFactory
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
        - RewardToken
        - Token
      abis:
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: MegaFactory
          file: ./abis/MegaFactory.json
        - name: PotPool
          file: ./abis/PotPool.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
        - name: UniswapPairContract
          file: ./abis/UniswapV2Pair.json
      eventHandlers:
        - event: DeploymentCompleted(string)
          handler: handleDeploymentCompleted
      file: ./src/megaFactory.ts

templates:
  - kind: ethereum/contract
    name: Vault
    network: {{ network }}
    source:
      abi: VaultContract
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
      abis:
        - name: VaultContract
          file: ./abis/Vault.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
        - name: UniswapPairContract
          file: ./abis/UniswapV2Pair.json
      eventHandlers:
        - event: Deposit(indexed address,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256)
          handler: handleWithdraw
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./src/vault.ts

  - kind: ethereum/contract
    name: Strategy
    network: {{ network }}
    source:
      abi: Strategy
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - _Strategy
      abis:
        - name: Strategy
          file: ./abis/Strategy.json
        - name: ERC20Contract
          file: ./abis/ERC20.json
        - name: ChainLinkContract
          file: ./abis/ChainLink.json
        - name: YearnLensContract
          file: ./abis/YearnLens.json
        - name: UniswapRouterContract
          file: ./abis/UniswapRouter.json
        - name: UniswapPairContract
          file: ./abis/UniswapV2Pair.json
      eventHandlers:
        - event: ProfitLogInReward(uint256,uint256,uint256)
          handler: handleProfitLogInReward
      file: ./src/strategy.ts

  - kind: ethereum/contract
    name: PotPool
    network: {{ network }}
    source:
      abi: PotPool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
      abis:
        - name: PotPool
          file: ./abis/PotPool.json
      eventHandlers:
        - event: Staked(indexed address,uint256)
          handler: handleStaked
        - event: Withdrawn(indexed address,uint256)
          handler: handleWithdrawn
      file: ./src/potPool.ts
  
  - kind: ethereum/contract
    name: NoMintRewardPool
    network: {{ network }}
    source:
      abi: NoMintRewardPool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Vault
      abis:
        - name: NoMintRewardPool
          file: ./abis/NoMintRewardPool.json
      eventHandlers:
        - event: Staked(indexed address,uint256)
          handler: handleStaked
        - event: Withdrawn(indexed address,uint256)
          handler: handleWithdrawn
      file: ./src/noMintRewardPool.ts