specVersion: 0.0.5
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: rocketStorage
    network: mainnet
    source:
      address: "0x1d8f8f00cfa6758d7bE78336684788Fb0ee0Fa46"
      abi: RocketStorage
      startBlock: 13325233
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Staker
        - RocketETHTransaction
      abis:
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      callHandlers:
        - function: setAddress(bytes32,address)
          handler: handleSetAddress
      file: ./src/mappings/rocketStorage.ts
templates:
  - kind: ethereum/contract
    name: rocketTokenRETH
    network: mainnet
    source:
      abi: rocketTokenRETH
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Staker
        - RocketETHTransaction
      abis:
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./src/mappings/rocketTokenRETHMapping.ts
  - kind: ethereum/contract
    name: rocketNetworkBalances
    network: mainnet
    source:
      abi: rocketNetworkBalances
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NetworkStakerBalanceCheckpoint
        - StakerBalanceCheckpoint
      abis:
        - name: rocketNetworkBalances
          file: ./abis/RocketNetworkBalances.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: rocketDepositPool
          file: ./abis/RocketDepositPool.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        - name: rocketVault
          file: ./abis/RocketVault.json
        - name: rocketNodeStaking
          file: ./abis/RocketNodeStaking.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: BalancesUpdated(uint256,uint256,uint256,uint256,uint256)
          handler: handleBalancesUpdated
      file: ./src/mappings/rocketNetworkBalancesMapping.ts
  - kind: ethereum/contract
    name: rocketNodeManager
    network: mainnet
    source:
      abi: rocketNodeManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Node
        - NetworkNodeTimezone
      abis:
        - name: rocketNodeManager
          file: ./abis/RocketNodeManager.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
      eventHandlers:
        - event: NodeRegistered(indexed address,uint256)
          handler: handleNodeRegister
        - event: NodeTimezoneLocationSet(indexed address,uint256)
          handler: handleNodeTimezoneChanged
      file: ./src/mappings/rocketNodeManager.ts
  - kind: ethereum/contract
    name: rocketNodeStaking
    network: mainnet
    source:
      abi: rocketNodeStaking
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NodeRPLStakeTransaction
      abis:
        - name: rocketNodeStaking
          file: ./abis/RocketNodeStaking.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: RPLStaked(indexed address,uint256,uint256)
          handler: handleRPLStaked
        - event: RPLWithdrawn(indexed address,uint256,uint256)
          handler: handleRPLWithdrawn
        - event: RPLSlashed(indexed address,uint256,uint256,uint256)
          handler: handleRPLSlashed
      file: ./src/mappings/rocketNodeStakingMapping.ts
  - kind: ethereum/contract
    name: rocketRewardsPool
    network: mainnet
    source:
      abi: rocketRewardsPool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - RPLRewardInterval
        - RPLRewardClaim
      abis:
        - name: rocketRewardsPool
          file: ./abis/RocketRewardsPool.json
        - name: rocketDAONodeTrusted
          file: ./abis/RocketDAONodeTrusted.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: RPLTokensClaimed(indexed address,indexed address,uint256,uint256)
          handler: handleRPLTokensClaimed
        - event: RewardSnapshot(indexed uint256,(uint256,uint256,uint256,bytes32,string,uint256,uint256,uint256[],uint256[],uint256[],uint256),uint256,uint256,uint256)
          handler: handleRewardSnapshot
      file: ./src/mappings/rocketRewardsPoolMapping.ts
  - kind: ethereum/contract
    name: rocketNetworkPrices
    network: mainnet
    source:
      abi: rocketNetworkPrices
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NetworkNodeBalanceCheckpoint
        - NodeBalanceCheckpoint
      abis:
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketNetworkFees
          file: ./abis/RocketNetworkFees.json
        - name: rocketDAOProtocolSettingsNode
          file: ./abis/RocketDAOProtocolSettingsNode.json
        - name: rocketDAOProtocolSettingsMinipool
          file: ./abis/RocketDAOProtocolSettingsMinipool.json
        - name: rocketNodeStaking
          file: ./abis/RocketNodeStaking.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: PricesUpdated(uint256,uint256,uint256,uint256)
          handler: handlePricesUpdated
        - event: PricesUpdated(uint256,uint256,uint256)
          handler: handlePricesUpdatedAtlas
      file: ./src/mappings/rocketNetworkPricesMapping.ts
  - kind: ethereum/contract
    name: rocketMinipoolManager
    network: mainnet
    source:
      abi: rocketMinipoolManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Minipool
      abis:
        - name: rocketMinipoolManager
          file: ./abis/RocketMinipoolManager.json
        - name: rocketNetworkFees
          file: ./abis/RocketNetworkFees.json
        - name: rocketNodeStaking
          file: ./abis/RocketNodeStaking.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
      eventHandlers:
        - event: MinipoolCreated(indexed address,indexed address,uint256)
          handler: handleMinipoolCreated
        - event: MinipoolDestroyed(indexed address,indexed address,uint256)
          handler: handleMinipoolDestroyed
      file: ./src/mappings/rocketMinipoolManager.ts
  - kind: ethereum/contract
    name: rocketMinipoolqueue
    network: mainnet
    source:
      abi: rocketMinipoolqueue
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Minipool
      abis:
        - name: rocketMinipoolqueue
          file: ./abis/RocketMinipoolQueue.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
      eventHandlers:
        - event: MinipoolEnqueued(indexed address,indexed bytes32,uint256)
          handler: handleMinipoolEnqueued
        - event: MinipoolDequeued(indexed address,indexed bytes32,uint256)
          handler: handleMinipoolDequeued
      file: ./src/mappings/rocketMinipoolQueueMapping.ts
  - kind: ethereum/contract
    name: rocketDAONodeTrustedActions
    network: mainnet
    source:
      abi: rocketDAONodeTrustedActions
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Node
      abis:
        - name: rocketDAONodeTrustedActions
          file: ./abis/RocketDAONodeTrustedActions.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
      eventHandlers:
        - event: ActionJoined(indexed address,uint256,uint256)
          handler: handleOracleNodeJoined
        - event: ActionLeave(indexed address,uint256,uint256)
          handler: handleOracleNodeLeft
        - event: ActionKick(indexed address,uint256,uint256)
          handler: handleOracleNodeKicked
        - event: ActionChallengeDecided(indexed address,indexed address,bool,uint256)
          handler: handleChallengeDecided
      file: ./src/mappings/rocketDAONodeTrustedActionMapping.ts
  - name: rocketMinipoolDelegate
    kind: ethereum/contract
    network: mainnet
    source:
      abi: rocketMinipoolDelegate
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/rocketMinipoolDelegate.ts
      entities:
        - Minipool
        - Node
      abis:
        - name: rocketMinipoolDelegate
          file: ./abis/RocketMinipoolDelegate.json
        - name: rocketNetworkPrices
          file: ./abis/RocketNetworkPrices.json
        - name: rocketTokenRETH
          file: ./abis/RocketTokenRETH.json
        - name: RocketStorage
          file: ./abis/RocketStorage.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
      eventHandlers:
        - event: StatusUpdated(indexed uint8,uint256)
          handler: handleStatusUpdated
        - event: EtherDeposited(indexed address,uint256,uint256)
          handler: handleEtherDeposited
