specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: TokenholderGovernor
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: TokenholderGovernor
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: TokenholderGovernor
          file: ./abis/threshold-governance/TokenholderGovernor.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
          handler: handleProposalCreated
        - event: ProposalExecuted(uint256)
          handler: handleProposalExecuted
        - event: ProposalExtended(indexed uint256,uint64)
          handler: handleProposalExtended
        - event: ProposalQueued(uint256,uint256)
          handler: handleProposalQueued
        - event: QuorumNumeratorUpdated(uint256,uint256)
          handler: handleQuorumNumeratorUpdated
        - event: TimelockChange(address,address)
          handler: handleTimelockChange
        - event: VoteCast(indexed address,uint256,uint8,uint256,string)
          handler: handleVoteCast
        - event: VotingDelaySet(uint256,uint256)
          handler: handleVotingDelaySet
        - event: VotingPeriodSet(uint256,uint256)
          handler: handleVotingPeriodSet
      file: ./protocols/threshold-governance/src/tokenholder-governor.ts
  - kind: ethereum/contract
    name: T
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: T
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: T
          file: ./abis/threshold-governance/T.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,indexed address)
          handler: handleDelegateChanged
        - event: DelegateVotesChanged(indexed address,uint256,uint256)
          handler: handleDelegateVotesChanged
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/threshold-governance/src/t.ts