specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: HOPGovernor
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: HOPGovernor
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: HOPGovernor
          file: ./abis/hop-governance/HOPGovernor.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
          handler: handleProposalCreated
        - event: ProposalExecuted(uint256)
          handler: handleProposalExecuted
        - event: ProposalQueued(uint256,uint256)
          handler: handleProposalQueued
        - event: QuorumNumeratorUpdated(uint256,uint256)
          handler: handleQuorumNumeratorUpdated
        - event: TimelockChange(address,address)
          handler: handleTimelockChange
        - event: VoteCast(indexed address,uint256,uint8,uint256,string)
          handler: handleVoteCast
      file: ./protocols/hop-governance/src/hop-governor.ts
  - kind: ethereum/contract
    name: HOPToken
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: HOPToken
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: HOPToken
          file: ./abis/hop-governance/HOPToken.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,indexed address)
          handler: handleDelegateChanged
        - event: DelegateVotesChanged(indexed address,uint256,uint256)
          handler: handleDelegateVotesChanged
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/hop-governance/src/hop-token.ts