specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: BiswapFactory
    network: bsc
    source:
      address: "0x858e3312ed3a876947ea49d572a7c42de08af7ee"
      abi: BiswapFactory
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - PairCreated
      abis:
        - name: BiswapFactory
          file: ./abis/BiswapFactory.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/biswap-factory.ts
