specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
features:
  - grafting
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: Factory
    network: {{network}}
    source:
      address: "{{factoryAddress}}"
      abi: Factory
      startBlock: {{factoryAddressStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/factory.ts
      entities:
        - Token
        - DexAmmProtocol
        - LiquidityPool
        - Protocol
        - _PricesUSD
        - _TokenTracker
        - _LiquidityPoolAmount
      abis:
        - name: Pool
          file: ./abis/uniswap-v3/Pool.json
        - name: Factory
          file: ./abis/uniswap-v3/Factory.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: PoolCreated(indexed address,indexed address,indexed uint24,int24,address)
          handler: handlePoolCreated
templates:
  - kind: ethereum/contract
    name: Pool
    network: {{network}}
    source:
      abi: Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/core.ts
      entities:
        - LiqudityPool
        - Token
        - Deposit
        - Withdraw
        - Swap
        - LiquidityPool
        - DexAmmProtocol
        - Token
        - UsageMetricsDailySnapshot
        - FinancialsDailySnapshot
        - PoolDailySnapshot
        - _PricesUSD
        - _Account
        - _DailyActiveAccount
        - _TokenTracker
        - _LiquidityPoolAmount
      abis:
        - name: Pool
          file: ./abis/uniswap-v3/Pool.json
        - name: Factory
          file: ./abis/uniswap-v3/Factory.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Initialize(uint160,int24)
          handler: handleInitialize
        - event: Swap(indexed address,indexed address,int256,int256,uint160,uint128,int24)
          handler: handleSwap
