export const protocolErrorMessages = {
    tvlRange: "Protocol level totalValueLockedUSD out of normal range. The protocols listed below have greater than $10000 or less than $100000000000.",
    cumulativeSupplySideRev: "Protocol level cumulativeSupplySideRevenueUSD out of normal range. The protocols listed below have less than $1000 or greater than $100000000000.",
    cumulativeProtocolSideRev: "Protocol level cumulativeProtocolSideRev out of normal range. The protocols listed below have less than $1000 or greater than $100000000000.",
    cumulativeTotalRev: "Protocol level cumulativeTotalRevenueUSD has an unexpected value. The protocols listed below have a cumulativeTotalRevenueUSD that does not equal cumulativeProtocolSideRevenueUSD + cumulativeSupplySideRevenueUSD.",
    cumulativeVol: "Protocol level cumulativeVolumeUSD out of normal range. The protocols listed below have less than $10000.",
    cumulativeUniqueUsers: "Protocol level cumulativeUniqueUsers out of normal range. The protocols listed below have less than 100 or greater than 100000000 unique users.",
    totalPoolCount: "Protocol level totalPoolCount out of normal range. The protocols listed below have 0 pools or greater than 10000 pools.",
    cumulativeUniqueDepos: "Protocol level cumulativeUniqueDepositors has an unexpected value. The protocols listed below have less cumulative unique users than cumulative unique depositors.",
    cumulativeUniqueBorrowers: "Protocol level cumulativeUniqueBorrowers has an unexpected value. The protocols listed below have less cumulative unique users than cumulative unique borrowers.",
    cumulativeUniqueLiquidators: "Protocol level cumulativeUniqueLiquidators has an unexpected value. The protocols listed below have less cumulative unique users than cumulative unique liquidators.",
    cumulativeUniqueLiquidatees: "Protocol level cumulativeUniqueLiquidatees has an unexpected value. The protocols listed below have less cumulative unique users than cumulative unique liquidatees.",
    openPositionCount: "Protocol level openPositionCount out of normal range. The protocols listed below have less than 100 or greater than 1000000000.",
    cumulativePositionCount: "Protocol level cumulativePositionCount has an unexpected value. The protocols listed below have a lower openPositionCount than cumulativePositionCount.",
    totalDepoBal: "Protocol level totalDepositBalanceUSD out of normal range. The protocols listed below have less than $1000 or greater than $100000000000.",
    cumulativeDepo: "Protocol level cumulativeDepositUSD has an unexpected value. The protocols listed below have a lower cumulativeDepositUSD than totalDepositBalanceUSD.",
    totalBorrowBal: "Protocol level totalBorrowBalanceUSD has an unexpected value. The protocols listed below have a lower totalDepositBalanceUSD than totalBorrowBalanceUSD.",
    cumulativeLiquidate: "Protocol level cumulativeLiquidateUSD has an unexpected value. The protocols listed below have a lower cumulativeBorrowUSD than cumulativeLiquidateUSD.",
}
