specVersion: 0.0.5
repository: https://github.com/messari/subgraphs
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{subgraphId}}
  block: {{graftStartBlock}}
{{/graftEnabled}}
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Vault
    network: {{network}}
    source:
      address: "{{vaultAddress}}"
      abi: Vault
      startBlock: {{vaultStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DexAmmProtocol
      abis:
        - name: Vault
          file: ./abis/beethoven-x/Vault.json
        - name: WeightedPool
          file: ./abis/beethoven-x/WeightedPool.json
        - name: FeesCollector
          file: ./abis/beethoven-x/ProtocolFeesCollector.json
        - name: ERC20
          file: ./abis/beethoven-x/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: PoolRegistered(indexed bytes32,indexed address,uint8)
          handler: handlePoolRegistered
        - event: TokensRegistered(indexed bytes32,address[],address[])
          handler: handleTokensRegistered
        - event: PoolBalanceChanged(indexed bytes32,indexed address,address[],int256[],uint256[])
          handler: handlePoolBalanceChanged
        - event: Swap(indexed bytes32,indexed address,indexed address,uint256,uint256)
          handler: handleSwap
      file: ./src/mappings/vaultMappings.ts


  - kind: ethereum/contract
    name: GaugeController
    network: {{network}}
    source:
      address: "{{gaugeControllerAddress}}"
      abi: GaugeController
      startBlock: {{gaugeControllerStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DexAmmProtocol
      abis:
        - name: GaugeController
          file: ./abis/beethoven-x/GaugeController.json
        
      eventHandlers:
        - event: NewGauge(address,int128,uint256)
          handler: handleNewGauge
        - event: RewardsOnlyGaugeCreated(indexed address,indexed address,address)
          handler: handleRewardsOnlyGaugeCreated
      file: ./src/mappings/GaugeControllerMappings.ts

templates:
  - kind: ethereum/contract
    name: WeightedPool
    network: {{network}}
    source:
      abi: WeightedPool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WeightedPool
        - LiquidityPoolFee
      abis:
        - name: WeightedPool
          file: ./abis/beethoven-x/WeightedPool.json
        - name: FeesCollector
          file: ./abis/beethoven-x/ProtocolFeesCollector.json
      eventHandlers:
        - event: SwapFeePercentageChanged(uint256)
          handler: handleSwapFeePercentageChange
      file: ./src/mappings/poolMappings.ts

  - kind: ethereum/contract
    name: Gauge
    network: {{network}}
    source:
      abi: Gauge
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WeightedPool
        - LiquidityPoolFee
      abis:
        - name: Gauge
          file: ./abis/beethoven-x/Gauge.json
        - name: GaugeController
          file: ./abis/beethoven-x/GaugeController.json
        - name: ERC20
          file: ./abis/beethoven-x/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json

      eventHandlers:
        - event: Deposit(indexed address,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256)
          handler: handleWithdraw
        - event: UpdateLiquidityLimit(indexed address,uint256,uint256,uint256,uint256)
          handler: handleUpdateLiquidityLimit
      file: ./src/mappings/gaugeMappings.ts
