specVersion: 0.0.4
features:
  - ipfsOnEthereumContracts
description: ERC721 Metadata
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: ERC721
    network: mainnet
    source:
      abi: ERC721
      startBlock: 5806610
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Token
        - Attribute
        - ERC721Collection
        - NonERC721Collection
      abis:
        - name: ERC721
          file: ./abis/ERC721.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./src/mappings/collection.ts
