specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
features:
  - ipfsOnEthereumContracts
dataSources:
  - kind: ethereum/contract
    name: DydxGovernor
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: DydxGovernor
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: DydxGovernor
          file: ./abis/dydx-governance/DydxGovernor.json
        - name: Executor
          file: ./abis/dydx-governance/Executor.json
        - name: GovernanceStrategy
          file: ./abis/dydx-governance/GovernanceStrategy.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,indexed address,indexed
            address,address[],uint256[],string[],bytes[],bool[],uint256,uint256,address,bytes32)
          handler: handleProposalCreated
        - event: ProposalExecuted(uint256,indexed address)
          handler: handleProposalExecuted
        - event: ProposalQueued(uint256,uint256,indexed address)
          handler: handleProposalQueued
        - event: VoteEmitted(uint256,indexed address,bool,uint256)
          handler: handleVoteEmitted
        - event: VotingDelayChanged(uint256,indexed address)
          handler: handleVotingDelayChanged
      file: ./protocols/dydx-governance/src/dydx-governor.ts
  - kind: ethereum/contract
    name: DydxToken
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: DydxToken
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: DydxToken
          file: ./abis/dydx-governance/DydxToken.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,uint8)
          handler: handleDelegateChanged
        - event: DelegatedPowerChanged(indexed address,uint256,uint8)
          handler: handleDelegatedPowerChanged
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/dydx-governance/src/dydx-token.ts