specVersion: 0.0.5
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{subgraphId}}
  block: {{graftStartBlock}}
{{/graftEnabled}}
schema:
  file: ./schema.graphql
dataSources:
  {{#vaults}}
  - kind: ethereum/contract
    name: "{{name}}"
    network: mainnet
    source:
      address: "{{address}}"
      abi: RibbonThetaVaultWithSwap
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/vault.ts
      entities:
        - Vault
        - VaultShortPosition
        - VaultAccount
        - BalanceUpdate
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: RibbonVaultPauser
          file: ./abis/RibbonVaultPauser.json
        - name: Otoken
          file: ./abis/Otoken.json
        - name: OptionTokenV1
          file: ./abis/OptionTokenV1.json
        - name: OptionsPremiumPricer
          file: ./abis/OptionsPremiumPricer.json
        - name: ERC20
          file: ./abis/ERC20.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
          #V2
        - event: Deposit(indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: InstantWithdraw(indexed address,uint256,uint256)
          handler: handleInstantWithdraw
        - event: InitiateGnosisAuction(indexed address,indexed address,uint256,indexed address)
          handler: handleInitiateGnosisAuction
        - event: CollectVaultFees(uint256,uint256,uint256,indexed address)
          handler: handleCollectVaultFees
          #Earn Vaults
        - event: PayOptionYield(uint256,uint256,indexed address)
          handler: handlePayOptionYield
        - event: PurchaseOption(uint256,indexed address)
          handler: handlePurchaseOption
          #V1
        - event: Withdraw(indexed address,uint256,uint256,uint256)
          handler: handleWithdrawWithFee

  {{/vaults}}
    
  {{#liquidityGauges}}
  - kind: ethereum/contract
    name: "{{name}}"
    network: mainnet
    source:
      address: "{{address}}"
      abi: LiquidityGaugeV5
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/gauge.ts
      entities:
        - Vault
        - VaultTransaction
        - VaultAccount
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: LiquidityGaugeV5
          file: ./abis/LiquidityGaugeV5.json
        - name: RibbonVaultPauser
          file: ./abis/RibbonVaultPauser.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,uint256)
          handler: handleStake
        - event: Withdraw(indexed address,uint256)
          handler: handleUnstake
        - event: Staked(indexed address,uint256)
          handler: handleStaked
        - event: Withdrawn(indexed address,uint256)
          handler: handleWithdrawn
  {{/liquidityGauges}}

  - kind: ethereum/contract
    name: GnosisAuction
    network: mainnet
    source:
      address: "0x0b7fFc1f4AD541A4Ed16b40D8c37f0929158D101"
      abi: GnosisAuction
      startBlock: 13195539
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/vault.ts
      entities:
        - Vault
        - VaultShortPosition
        - VaultOptionTrade
        - VaultTransaction
        - VaultAccount
        - BalanceUpdate
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: GnosisAuction
          file: ./abis/GnosisEasyAuction.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: AuctionCleared(indexed uint256,uint96,uint96,bytes32)
          handler: handleAuctionCleared

  - kind: ethereum/contract
    name: RibbonSwapOld
    network: mainnet
    source:
      address: "0xF0E5c92cEdd66C7985C354C35e2bC37E685b99Da"
      abi: SwapContract
      startBlock: 14740669
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/vault.ts
      entities:
        - Vault
        - VaultShortPosition
        - VaultOptionTrade
        - VaultTransaction
        - VaultAccount
        - BalanceUpdate
        - SwapOffer
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: SwapContract
          file: ./abis/SwapContract.json
        - name: ERC20
          file: ./abis/ERC20.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Swap(indexed uint256,uint256,indexed address,uint256,uint256,address,uint256)
          handler: handleSwap
        - event: NewOffer(uint256,address,address,address,uint256,uint256,uint256)
          handler: handleNewOffer
  - kind: ethereum/contract
    name: RibbonSwap
    network: mainnet
    source:
      address: "0xEb8CAB2F4663247db8eAfb556F498c861bB4e161"
      abi: SwapContract
      startBlock: 15126067
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/vault.ts
      entities:
        - Vault
        - VaultShortPosition
        - VaultOptionTrade
        - VaultTransaction
        - VaultAccount
        - BalanceUpdate
        - SwapOffer
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: SwapContract
          file: ./abis/SwapContract.json
        - name: ERC20
          file: ./abis/ERC20.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Swap(indexed uint256,uint256,indexed address,uint256,uint256,address,uint256)
          handler: handleSwap
        - event: NewOffer(uint256,address,address,address,uint256,uint256,uint256)
          handler: handleNewOffer   

  - kind: ethereum/contract
    name: Airswap
    network: mainnet
    source:
      address: "0x4572f2554421Bd64Bef1c22c8a81840E8D496BeA"
      abi: Airswap
      startBlock: 11938402
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/vault.ts
      entities:
        - Vault
    
      abis:
        - name: Airswap
          file: ./abis/Airswap.json
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Swap(indexed uint256,uint256,indexed address,uint256,uint256,address,indexed address,uint256,uint256,address,address,uint256,uint256,address)
          handler: handleAirswap

  - name: GaugeController
    kind: ethereum/contract
    network: mainnet
    source:
      abi: GaugeController
      address: "0x0cb9cc35cEFa5622E8d25aF36dD56DE142eF6415"
      startBlock: 14285271

    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/gaugeController.ts
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: LiquidityGaugeV5
          file: ./abis/LiquidityGaugeV5.json
        - name: RibbonVaultPauser
          file: ./abis/RibbonVaultPauser.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      entities:
        - Vault
      eventHandlers:
        - event: NewGauge(address,int128,uint256)
          handler: handleNewGauge

templates:
  - name: LiquidityGauge
    kind: ethereum/contract
    network: mainnet
    source:
      abi: LiquidityGaugeV5
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/gauge.ts
      entities:
        - Vault
        - VaultTransaction
        - VaultAccount
      abis:
        - name: RibbonThetaVaultWithSwap
          file: ./abis/RibbonThetaVaultWithSwap.json
        - name: LiquidityGaugeV5
          file: ./abis/LiquidityGaugeV5.json
        - name: RibbonVaultPauser
          file: ./abis/RibbonVaultPauser.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: GaugeController
          file: ./abis/GaugeController.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Deposit(indexed address,uint256)
          handler: handleStake
        - event: Withdraw(indexed address,uint256)
          handler: handleUnstake
        - event: Staked(indexed address,uint256)
          handler: handleStaked
        - event: Withdrawn(indexed address,uint256)
          handler: handleWithdrawn

