specVersion: 0.0.4
{{#features}}
features:
  - grafting
graft:
  base: {{base}}
  block: {{block}}
{{/features}}
schema:
  file: ./schema.graphql
dataSources:
  {{#hypervisorOrphan}}
  - name: {{name}}
    kind: ethereum/contract
    network: {{network}}
    source:
      address: "{{address}}"
      abi: Hypervisor
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      file: ./src/mappings/handlers.ts
      entities:
        - YieldAggregator
        - Account
        - ActiveAccount
        - Deposit
        - Withdraw
        - Vault
        - VaultDailySnapshot
        - VaultHourlySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
        - FinancialsDailySnapshot
        - _UnderlyingToken
        - _Rebalance
      abis:
        - name: Hypervisor
          file: ./abis/Hypervisor.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Deposit(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleWithdraw
        - event: Rebalance(int24,uint256,uint256,uint256,uint256,uint256)
          handler: handleRebalance
  {{/hypervisorOrphan}}
  {{#hypeRegistry}}
  - name: {{name}}
    kind: ethereum/contract
    network: {{network}}
    source:
      address: "{{address}}"
      abi: HypeRegistry
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      file: ./src/mappings/handlers.ts
      entities:
        - YieldAggregator
        - Vault
        - VaultFee
        - Token
        - _UnderlyingToken
      abis:
        - name: HypeRegistry
          file: ./abis/HypeRegistry.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: Hypervisor
          file: ./abis/Hypervisor.json
      eventHandlers:
        - event: HypeAdded(address,uint256)
          handler: handleHypeAdded
  {{/hypeRegistry}}
templates:
  - name: Hypervisor
    kind: ethereum/contract
    network: {{network}}
    source:
      abi: Hypervisor
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      file: ./src/mappings/handlers.ts
      entities:
        - YieldAggregator
        - Account
        - ActiveAccount
        - Deposit
        - Withdraw
        - Vault
        - VaultDailySnapshot
        - VaultHourlySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
        - FinancialsDailySnapshot
        - _UnderlyingToken
        - _Rebalance
      abis:
        - name: Hypervisor
          file: ./abis/Hypervisor.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Deposit(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleWithdraw
        - event: Rebalance(int24,uint256,uint256,uint256,uint256,uint256)
          handler: handleRebalance
