specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: BentoBox
    network: {{network}}
    source:
      address: '{{BentoBoxAddress}}'
      abi: DegenBox
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LogDeploy
      abis:
        - name: DegenBox
          file: ./abis/DegenBox.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: Cauldron
          file: ./abis/Cauldron.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: LogDeploy(indexed address,bytes,indexed address)
          handler: handleLogDeploy
      file: ./src/mapping.ts

  # 1. DegenBox (if applicable)
  {{#DegenBoxEnabled}}
  - kind: ethereum
    name: DegenBox
    network: {{network}}
    source:
      address: '{{DegenBoxAddress}}'
      abi: DegenBox
      startBlock: {{DegenBoxStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LogDeploy
      abis:
        - name: DegenBox
          file: ./abis/DegenBox.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: Cauldron
          file: ./abis/Cauldron.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: LogDeploy(indexed address,bytes,indexed address)
          handler: handleLogDeploy
      file: ./src/mapping.ts
  {{/DegenBoxEnabled}}

  # 2. Spell (if applicable)
  {{#SpellEnabled}}
  - kind: ethereum
    name: Spell
    network: {{network}}
    source:
      address: '{{SpellAddress}}'
      abi: ERC20
      startBlock: {{SpellStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LogDeploy
      abis:
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: Cauldron
          file: ./abis/Cauldron.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./src/staking.ts
  {{/SpellEnabled}}

  # 3. OffchainAggregator (if applicable)
  {{#OffchainAggregatorEnabled}}
  - kind: ethereum
    name: OffchainAggregator
    network: {{network}}
    source:
      address: '{{OffchainAggregatorAddress}}'
      abi: OffchainAggregator
      startBlock: {{OffchainAggregatorStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LogDeploy
      abis:
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: Cauldron
          file: ./abis/Cauldron.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
        - name: OffchainAggregator
          file: ./abis/OffchainAggregator.json
      eventHandlers:
        - event: AnswerUpdated(indexed int256,indexed uint256,uint256)
          handler: handleAnswerUpdated
      file: ./src/common/prices/prices.ts
  {{/OffchainAggregatorEnabled}}
templates:
  - name: Cauldron
    kind: ethereum/contract
    network: {{network}}
    source:
      abi: Cauldron
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mapping.ts
      entities:
        - Market
      abis:
        - name: Cauldron
          file: ./abis/Cauldron.json
        - name: DegenBox
          file: ./abis/DegenBox.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: LogAddCollateral(indexed address,indexed address,uint256)
          handler: handleLogAddCollateral
        - event: LogRemoveCollateral(indexed address,indexed address,uint256)
          handler: handleLogRemoveCollateral
        - event: LogBorrow(indexed address,indexed address,uint256,uint256)
          handler: handleLogBorrow
        - event: LogRepay(indexed address,indexed address,uint256,uint256)
          handler: handleLogRepay
        - event: LogExchangeRate(uint256)
          handler: handleLogExchangeRate
        - event: LogAccrue(uint128)
          handler: handleLogAccrue
  - name: priceOracle
    kind: ethereum/contract
    network: {{network}}
    source:
      abi: PriceOracle
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/common/prices/prices.ts
      entities:
        - Market
      abis:
        - name: PriceOracle
          file: ./abis/PriceOracle.json
