specVersion: 0.0.4
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: RootChainManager
    network: {{ network }}
    source:
      address: "{{rootChainManager.address}}"
      abi: RootChainManager
      startBlock: {{ rootChainManager.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token 
        - CrosschainToken 
        - RewardToken 
        - Protocol 
        - UsageMetricsDailySnapshot 
        - FinancialsDailySnapshot 
        - UsageMetricsHourlySnapshot 
        - Pool 
        - PoolRoute 
        - PoolDailySnapshot 
        - PoolHourlySnapshot 
        - Account 
        - SupportedToken 
        - ActiveAccount 
        - _ActivityHelper 
        - _ProtocolSnapshotHelper 
        - _CircularBuffer 
      abis:
        - name: EtherPredicate
          file: ./abis/Polygon/EtherPredicate.json
        - name: ERC20Predicate
          file: ./abis/Polygon/ERC20Predicate.json
        - name: RootChainManager
          file: ./abis/Polygon/RootChainManager.json
        - name: FxERC20RootTunnel
          file: ./abis/Polygon/FxErc20RootTunnel.json
        
        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: PredicateRegistered(indexed bytes32,indexed address)
          handler: handlePredicateRegistered
        - event: TokenMapped(indexed address,indexed address,indexed bytes32)
          handler: handlePOSTokenMapped
      file: ./src/mappings/rootchainManager.ts
  
  - kind: ethereum/contract
    name: FxERC20Events
    network: {{ network }}
    source:
      abi: FxERC20RootTunnel
      startBlock: {{ fxERC20RootTunnel.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - CrosschainToken
        - RewardToken
        - Protocol
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
        - FinancialsDailySnapshot
        - Pool
        - PoolRoute
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Account
        - SupportedToken
        - ActiveAccount
        - _ActivityHelper
        - _ProtocolSnapshotHelper
        - _CircularBuffer
      abis:
        - name: EtherPredicate
          file: ./abis/Polygon/EtherPredicate.json
        - name: ERC20Predicate
          file: ./abis/Polygon/ERC20Predicate.json
        - name: RootChainManager
          file: ./abis/Polygon/RootChainManager.json
        - name: FxERC20RootTunnel
          file: ./abis/Polygon/FxErc20RootTunnel.json

        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: FxDepositERC20(indexed address,indexed address,indexed address,uint256)
          handler: handleFxDepositERC20
        - event: FxWithdrawERC20(indexed address,indexed address,indexed address,uint256)
          handler: handleFxWithdrawERC20
        - event: TokenMappedERC20(indexed address,indexed address)
          handler: handleTokenMappedERC20
      file: ./src/mappings/fxErc20.ts

templates:
  - name: Predicate
    kind: ethereum
    network: {{ network }}
    source:
      abi: ERC20Predicate
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token 
        - CrosschainToken 
        - RewardToken 
        - Protocol 
        - UsageMetricsDailySnapshot 
        - UsageMetricsHourlySnapshot 
        - FinancialsDailySnapshot 
        - Pool 
        - PoolRoute 
        - PoolDailySnapshot 
        - PoolHourlySnapshot 
        - Account 
        - SupportedToken 
        - ActiveAccount 
        - _ActivityHelper 
        - _ProtocolSnapshotHelper 
        - _CircularBuffer 
      abis:
        - name: EtherPredicate
          file: ./abis/Polygon/EtherPredicate.json
        - name: ERC20Predicate
          file: ./abis/Polygon/ERC20Predicate.json
        - name: RootChainManager
          file: ./abis/Polygon/RootChainManager.json
        - name: FxERC20RootTunnel
          file: ./abis/Polygon/FxErc20RootTunnel.json
        
        - name: ERC20
          file: ./abis/Tokens/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/Tokens/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/Tokens/ERC20NameBytes.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      callHandlers:
        - function: lockTokens(address,address,address,bytes)
          handler: handleLockTokens
        - function: exitTokens(address,address,bytes)
          handler: handleExitTokens
      file: ./src/mappings/predicate.ts