specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: OpenSea
    network: {{ network }}
    source:
      address: "{{address}}"
      abi: OpenSea
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: OpenSea
          file: ./abis/OpenSeaV2.json
        - name: ERC165
          file: ./abis/ERC165.json
        - name: NftMetadata
          file: ./abis/NftMetadata.json
      callHandlers:
        - function: atomicMatch_(address[14],uint256[18],uint8[8],bytes,bytes,bytes,bytes,bytes,bytes,uint8[2],bytes32[5])
          handler: handleMatch
      file: ./src/mappings.ts
