specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  {{#vaults}}
  - kind: ethereum
    name: {{ name }}
    network: {{ chain }}
    source:
      address: "{{ address }}"
      startBlock: {{ startBlock }}
      abi: Vault
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Deposit
        - Withdraw
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: BribesProcessor
          file: ./abis/BribesProcessor.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: Controller
          file: ./abis/Controller.json
        - name: BaseRewardPool
          file: ./abis/BaseRewardPool.json
        - name: RewardsLogger
          file: ./abis/RewardsLogger.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: PerformanceFeeGovernance(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handlePerformanceFeeGovernance
        - event: PerformanceFeeStrategist(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handlePerformanceFeeStrategist
        - event: TreeDistribution(indexed address,uint256,indexed uint256,uint256)
          handler: handleTreeDistribution
        - event: WithdrawalFee(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handleWithdrawalFee
        - event: Harvested(indexed address,uint256,indexed uint256,uint256)
          handler: handleHarvested
      callHandlers:
        - function: deposit(uint256)
          handler: handleDeposit
        - function: deposit(uint256,bytes32[])
          handler: handleDepositWithProof
        - function: depositAll()
          handler: handleDepositAll
        - function: depositAll(bytes32[])
          handler: handleDepositAllWithProof
        - function: depositFor(address,uint256)
          handler: handleDepositFor
        - function: depositFor(address,uint256,bytes32[])
          handler: handleDepositForWithProof
        - function: withdraw(uint256)
          handler: handleWithdraw
        - function: withdrawAll()
          handler: handleWithdrawAll
      file: ./src/mappings/vaultMappings.ts
  {{/vaults}}

  - kind: ethereum
    name: rewardsLogger
    network: {{ chain }}
    source:
      address: "{{ rewardsLoggerAddress }}"
      startBlock: {{ rewardsLoggerStartBlock }}
      abi: RewardsLogger
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Deposit
        - Withdraw
      abis:
        - name: RewardsLogger
          file: ./abis/RewardsLogger.json
        - name: Vault
          file: ./abis/Vault.json
        - name: BribesProcessor
          file: ./abis/BribesProcessor.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: Controller
          file: ./abis/Controller.json
        - name: BaseRewardPool
          file: ./abis/BaseRewardPool.json
        - name: DiggToken
          file: ./abis/DiggToken.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: UnlockScheduleSet(indexed address,address,uint256,uint256,uint256,uint256,indexed uint256,indexed uint256)
          handler: handleUnlockScheduleSet
      file: ./src/mappings/rewardsLoggerMappings.ts

templates: 
  - kind: ethereum
    name: Strategy
    network: {{ chain }}
    source:
      abi: Strategy
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Deposit
        - Withdraw
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: BribesProcessor
          file: ./abis/BribesProcessor.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: Controller
          file: ./abis/Controller.json
        - name: BaseRewardPool
          file: ./abis/BaseRewardPool.json
        - name: RewardsLogger
          file: ./abis/RewardsLogger.json
        - name: ERC20
          file: ./abis/ERC20.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: Upgraded(indexed address)
          handler: handleUpgraded
        - event: Harvest(uint256,indexed uint256)
          handler: handleHarvest
        - event: FarmHarvest(uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleFarmHarvest
        - event: HarvestState(uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleDiggHarvest
        - event: HarvestState(uint256,uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleHarvestState
        - event: CurveHarvest(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleCurveHarvest

        - event: SetWithdrawalFee(uint256)
          handler: handleSetWithdrawalFee
        - event: PerformanceFeeGovernance(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handlePerformanceFeeGovernance
        - event: SetPerformanceFeeGovernance(uint256)
          handler: handleSetPerformanceFeeGovernance
        - event: PerformanceFeeStrategist(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handlePerformanceFeeStrategist
        - event: SetPerformanceFeeStrategist(uint256)
          handler: handleSetPerformanceFeeStrategist
        
        - event: TreeDistribution(indexed address,uint256,indexed uint256,uint256)
          handler: handleTreeDistribution
      callHandlers:
        - function: setBribesProcessor(address)
          handler: handleSetBribesProcessor
      file: ./src/mappings/strategyMappings.ts
  - kind: ethereum
    name: Controller
    network: {{ chain }}
    source:
      abi: Controller
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Deposit
        - Withdraw
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: BribesProcessor
          file: ./abis/BribesProcessor.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: Controller
          file: ./abis/Controller.json
        - name: BaseRewardPool
          file: ./abis/BaseRewardPool.json
        - name: RewardsLogger
          file: ./abis/RewardsLogger.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      callHandlers:
        - function: setVault(address,address)
          handler: handleSetVault
        - function: setStrategy(address,address)
          handler: handleSetStrategy
      file: ./src/mappings/controllerMappings.ts
  - kind: ethereum
    name: BribesProcessor
    network: {{ chain }}
    source:
      abi: BribesProcessor
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Token
        - Deposit
        - Withdraw
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: BribesProcessor
          file: ./abis/BribesProcessor.json
        - name: Strategy
          file: ./abis/Strategy.json
        - name: Controller
          file: ./abis/Controller.json
        - name: BaseRewardPool
          file: ./abis/BaseRewardPool.json
        - name: RewardsLogger
          file: ./abis/RewardsLogger.json
        - name: ERC20
          file: ./abis/ERC20.json
        
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: InchOracleContract
          file: ./abis/Prices/InchOracle.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: BribeEmission(indexed address,indexed address,uint256)
          handler: handleBribeEmission
        - event: PerformanceFeeGovernance(indexed address,uint256)
          handler: handlePerformanceFeeGovernance
        - event: SentBribeToGovernance(indexed address,uint256)
          handler: handleSentBribeToGovernance
        - event: SentBribeToTree(indexed address,uint256)
          handler: handleSentBribeToTree
      file: ./src/mappings/bribesMappings.ts