specVersion: 0.0.4
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  # this section is for price oracle
  - kind: ethereum
    name: UniswapV2Factory
    network: {{ network }}
    source:
      abi: UniswapV2Factory
      startBlock: {{ AxelarGateway.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        - name: UniswapV2Factory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
      file: ./src/mappings.ts

  - kind: ethereum
    name: AxelarGateway
    network: {{ network }}
    source:
      address: "{{ AxelarGateway.address }}"
      startBlock: {{ AxelarGateway.startBlock }}
      abi: AxelarGateway
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: AxelarGateway
          file: ./abis/AxelarGateway.json
        - name: BurnableMintableCappedERC20
          file: ./abis/BurnableMintableCappedERC20.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: UniswapV2Factory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: TokenSent(indexed address,string,string,string,uint256)
          handler: handleTokenSend
        - event: TokenDeployed(string,address)
          handler: handleTokenDeployed
        - event: ContractCallWithToken(indexed address,string,string,indexed bytes32,bytes,string,uint256)
          handler: handleContractCallWithToken
        - event: ContractCall(indexed address,string,string,indexed bytes32,bytes)
          handler: handleContractCall
      callHandlers:
        - function: mintToken(bytes,bytes32)
          handler: handleMintToken
        - function: burnToken(bytes,bytes32)
          handler: handleBurnToken
      file: ./src/mappings.ts

templates:
  - name: BurnableMintableCappedERC20
    kind: ethereum/contract
    network: mainnet
    source:
      abi: BurnableMintableCappedERC20
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: AxelarGateway
          file: ./abis/AxelarGateway.json
        - name: BurnableMintableCappedERC20
          file: ./abis/BurnableMintableCappedERC20.json
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: UniswapV2Factory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTokenTransfer
      file: ./src/mappings.ts