name: Actions
on: merge
  pul_request: 
    branches:
      - master
    types: [closed]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      - run: |
	    echo "Github Action - Deploying subgraphs to Messari Hosted Service"
      npm install -g @graphprotocol/graph-cli
      graph auth --product hosted-service 0845de8b9d834db8b16b5c97ba33ec53
      cd subgraphs/uniswap-forks
      npm run deploy uniswap-v2 steegecs

 