on: 
  push:

jobs:
  Deployment: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 3

      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - id: deployment
        run: |
          echo "::set-env name=configs_before::$(git show ${{ github.event.before }}:./deployment/deployment.json)"
          echo "${{ env.configs_before }}"

      - uses: steegecs/Action-Subgraph-Deployment@payloads
        with: 
          HOSTED_SERVICE_ACCESS_TOKEN: ${{ secrets.HOSTED_SERVICE_ACCESS_TOKEN }}
          CHANGED_FILES: "${{ steps.files.outputs.all }}"
          ABSOLUTE_PATH: ${{ github.workspace }}
          GRAPH_DEPLOYMENT_LOCATION: messari
          COMMIT_BEFORE_PUSH: "${{ env.configs_before }}"
          COMMIT_AFTER_PUSH: "${{ github.event.after }}"

      # - uses: steegecs/Messari-Deployment-Config-Reset@main
      #   with: 
      #     ABSOLUTE_PATH: ${{ github.workspace }}

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     add: '.'
      #     commit: --signoff
      #     push: true

