name: Version Handler
on: 
  commit: 
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Update subgraph version in constants file if relevant file changed
        run: | 
          CHANGED_FILES="${{ steps.files.outputs.all }}" ABSOLUTE_PATH=${GITHUB_WORKSPACE} python3 src/schemaVersionUpdate.py
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '.'
          message: 'Updated subgraph versions and fork version if changes made to relavent /src/ folder'
