name: Version Handler
on: 
  push: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Execute Python Script
        run: | 
          CHANGED_FILES="${{ steps.files.outputs.all }}" ABSOLUTE_PATH=${GITHUB_WORKSPACE} python3 src/subgraphVersionUpdate.py
    
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '.'
          message: 'Updated subgraph versions and fork version if changes made to relavent /src/ folder'

      - name: Update the README document with any updated versions
        run: | 
          CHANGED_FILES="${{ steps.files.outputs.all }}" ABSOLUTE_PATH=${GITHUB_WORKSPACE} python3 src/schemaVersionUpdate.py
              